use std::collections::BTreeMap;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use chrono::Utc;
use clap::Args;
use ed25519_dalek::Signer;
use serde_json::Value;

use crate::manifest::Manifest;
use crate::package;
use crate::signing::{self, SignatureMetadata, StoredKey};

#[derive(Args, Debug, Clone)]
pub struct SignArgs {
    /// Package root directory
    #[arg(long, default_value = ".")]
    pub root: PathBuf,
    /// Path to developer key file (JSON generated by adep keygen)
    #[arg(long, default_value = "keys/developer.json")]
    pub key: PathBuf,
    /// Optional manifest path (defaults to <root>/manifest.json)
    #[arg(long)]
    pub manifest: Option<PathBuf>,
    /// Logical signer name stored in metadata
    #[arg(long)]
    pub signer: Option<String>,
    /// Extra metadata entries (key=value)
    #[arg(long = "meta", value_parser = parse_key_value)]
    pub metadata: Vec<(String, String)>,
}

pub fn run(args: &SignArgs) -> Result<()> {
    let cwd = std::env::current_dir().context("failed to resolve current directory")?;
    let root = if args.root.is_absolute() {
        args.root.clone()
    } else {
        cwd.join(&args.root)
    };

    let key_path = if args.key.is_absolute() {
        args.key.clone()
    } else {
        root.join(&args.key)
    };

    let stored = StoredKey::read(&key_path)
        .with_context(|| format!("failed to read key file {}", key_path.display()))?;
    let keypair = stored.to_keypair()?;
    let developer_key = stored.developer_key_fingerprint();

    let manifest_path = args
        .manifest
        .clone()
        .unwrap_or_else(|| root.join("manifest.json"));

    let mut manifest = Manifest::load(&manifest_path)
        .with_context(|| format!("failed to read {}", manifest_path.display()))?;

    let mut manifest_dirty = false;
    match manifest.developer_key.as_ref() {
        Some(existing) if existing == &developer_key => {}
        Some(existing) => {
            bail!(
                "manifest developer_key ({existing}) does not match key file public component ({developer_key})"
            );
        }
        None => {
            manifest.developer_key = Some(developer_key.clone());
            manifest_dirty = true;
        }
    }

    if manifest_dirty {
        manifest
            .save(&manifest_path)
            .with_context(|| format!("failed to update {}", manifest_path.display()))?;
    }

    let manifest_sha = package::update_manifest_hash(&root, &manifest_path)?;
    let package_digest = package::compute_package_digest(&root)?;

    let signature_bytes = keypair.sign(package_digest.as_bytes());

    let mut extra = BTreeMap::new();
    for (key, value) in &args.metadata {
        extra.insert(key.clone(), Value::String(value.clone()));
    }

    let metadata = SignatureMetadata {
        package_sha256: package_digest.clone(),
        manifest_sha256: manifest_sha,
        signer: args.signer.clone(),
        timestamp: Utc::now(),
        extra,
    };

    let sig_path = root.join("_sig").join("developer.sig");
    signing::write_signature_file(&sig_path, &keypair.public, &signature_bytes, &metadata)?;

    println!("Signed package digest {}", package_digest);
    println!("Signature written to {}", sig_path.display());

    Ok(())
}

fn parse_key_value(raw: &str) -> Result<(String, String), String> {
    match raw.split_once('=') {
        Some((k, v)) if !k.is_empty() => Ok((k.to_string(), v.to_string())),
        _ => Err("metadata must be in key=value format".to_string()),
    }
}
