// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: coordinator/v1/coordinator.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw TOML content from capsule.toml
	TomlContent   []byte `protobuf:"bytes,1,opt,name=toml_content,json=tomlContent,proto3" json:"toml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetTomlContent() []byte {
	if x != nil {
		return x.TomlContent
	}
	return nil
}

type DeployResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	// URL where the capsule is accessible (e.g. http://myapp.gumball.local)
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *DeployResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capsules      []*CapsuleInfo         `protobuf:"bytes,1,rep,name=capsules,proto3" json:"capsules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetCapsules() []*CapsuleInfo {
	if x != nil {
		return x.Capsules
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CapsuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleInfo) Reset() {
	*x = CapsuleInfo{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleInfo) ProtoMessage() {}

func (x *CapsuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleInfo.ProtoReflect.Descriptor instead.
func (*CapsuleInfo) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *CapsuleInfo) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *CapsuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapsuleInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CapsuleInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	" coordinator/v1/coordinator.proto\x12\x1aonescluster.coordinator.v1\"2\n" +
	"\rDeployRequest\x12!\n" +
	"\ftoml_content\x18\x01 \x01(\fR\vtomlContent\"A\n" +
	"\x0eDeployResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\r\n" +
	"\vListRequest\"S\n" +
	"\fListResponse\x12C\n" +
	"\bcapsules\x18\x01 \x03(\v2'.onescluster.coordinator.v1.CapsuleInfoR\bcapsules\",\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\vCapsuleInfo\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url2\xc1\x02\n" +
	"\x12CoordinatorService\x12f\n" +
	"\rDeployCapsule\x12).onescluster.coordinator.v1.DeployRequest\x1a*.onescluster.coordinator.v1.DeployResponse\x12a\n" +
	"\fListCapsules\x12'.onescluster.coordinator.v1.ListRequest\x1a(.onescluster.coordinator.v1.ListResponse\x12`\n" +
	"\vStopCapsule\x12'.onescluster.coordinator.v1.StopRequest\x1a(.onescluster.coordinator.v1.StopResponseBKZIgithub.com/onescluster/coordinator/pkg/proto/coordinator/v1;coordinatorv1b\x06proto3"

var (
	file_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_v1_coordinator_proto_rawDesc), len(file_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_coordinator_v1_coordinator_proto_rawDescData
}

var file_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coordinator_v1_coordinator_proto_goTypes = []any{
	(*DeployRequest)(nil),  // 0: onescluster.coordinator.v1.DeployRequest
	(*DeployResponse)(nil), // 1: onescluster.coordinator.v1.DeployResponse
	(*ListRequest)(nil),    // 2: onescluster.coordinator.v1.ListRequest
	(*ListResponse)(nil),   // 3: onescluster.coordinator.v1.ListResponse
	(*StopRequest)(nil),    // 4: onescluster.coordinator.v1.StopRequest
	(*StopResponse)(nil),   // 5: onescluster.coordinator.v1.StopResponse
	(*CapsuleInfo)(nil),    // 6: onescluster.coordinator.v1.CapsuleInfo
}
var file_coordinator_v1_coordinator_proto_depIdxs = []int32{
	6, // 0: onescluster.coordinator.v1.ListResponse.capsules:type_name -> onescluster.coordinator.v1.CapsuleInfo
	0, // 1: onescluster.coordinator.v1.CoordinatorService.DeployCapsule:input_type -> onescluster.coordinator.v1.DeployRequest
	2, // 2: onescluster.coordinator.v1.CoordinatorService.ListCapsules:input_type -> onescluster.coordinator.v1.ListRequest
	4, // 3: onescluster.coordinator.v1.CoordinatorService.StopCapsule:input_type -> onescluster.coordinator.v1.StopRequest
	1, // 4: onescluster.coordinator.v1.CoordinatorService.DeployCapsule:output_type -> onescluster.coordinator.v1.DeployResponse
	3, // 5: onescluster.coordinator.v1.CoordinatorService.ListCapsules:output_type -> onescluster.coordinator.v1.ListResponse
	5, // 6: onescluster.coordinator.v1.CoordinatorService.StopCapsule:output_type -> onescluster.coordinator.v1.StopResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coordinator_v1_coordinator_proto_init() }
func file_coordinator_v1_coordinator_proto_init() {
	if File_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_v1_coordinator_proto_rawDesc), len(file_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_v1_coordinator_proto = out.File
	file_coordinator_v1_coordinator_proto_goTypes = nil
	file_coordinator_v1_coordinator_proto_depIdxs = nil
}
