mod typescript;

use anyhow::{bail, Context, Result};
use libadep_core::manifest::Manifest;
use schemars::schema::RootSchema;
use schemars::schema_for;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use typescript::generate_typescript;

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("schema-export") => schema_export(),
        Some(cmd) => bail!("unknown xtask command: {cmd}"),
        None => {
            print_usage();
            Ok(())
        }
    }
}

fn print_usage() {
    eprintln!(
        "Usage:\n  cargo xtask schema-export    # export manifest schema + TypeScript bindings"
    );
}

fn schema_export() -> Result<()> {
    let schema: RootSchema = schema_for!(Manifest);
    let repo_root = repo_root()?;

    let schema_path = repo_root
        .join("gumball-platform/packages/control-core/src/schemas/libadep_manifest.schema.json");
    let control_ts_path =
        repo_root.join("gumball-platform/packages/control-core/src/generated/libadepManifest.ts");
    let shared_ts_path =
        repo_root.join("bestyai-suite/packages/shared-ui/src/libadep/generated/libadepManifest.ts");

    let schema_json = serde_json::to_string_pretty(&schema)?;
    write_if_changed(&schema_path, format_json_comment(&schema_json))?;

    let ts_src = generate_typescript(&schema)?;
    write_if_changed(&control_ts_path, ts_src.clone())?;
    write_if_changed(&shared_ts_path, ts_src)?;

    println!("Schema written to {}", schema_path.display());
    println!("TypeScript written to {}", control_ts_path.display());
    println!("TypeScript written to {}", shared_ts_path.display());
    Ok(())
}

fn format_json_comment(content: &str) -> String {
    let mut out = String::from("// Auto-generated by cargo xtask schema-export. Do not edit.\n");
    out.push_str(content);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn repo_root() -> Result<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent() // gumball-adep/libadep
        .and_then(Path::parent) // gumball-adep
        .and_then(Path::parent) // monorepo root
        .map(Path::to_path_buf)
        .context("failed to resolve repository root from xtask manifest dir")
}

fn write_if_changed(path: &Path, contents: String) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let normalized = if contents.ends_with('\n') {
        contents
    } else {
        let mut tmp = contents;
        tmp.push('\n');
        tmp
    };

    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != normalized,
        Err(_) => true,
    };

    if needs_write {
        fs::write(path, normalized)?;
    }
    Ok(())
}
