use anyhow::{bail, Context, Result};
use schemars::schema::{
    ArrayValidation, InstanceType, ObjectValidation, RootSchema, Schema, SchemaObject, SingleOrVec,
};
use serde_json::Value;
use std::collections::{BTreeSet, HashMap};

pub fn generate_typescript(schema: &RootSchema) -> Result<String> {
    let mut generator = TypeGenerator::new(schema);
    for (name, definition) in &schema.definitions {
        generator.ensure_named(name, definition)?;
    }
    generator.ensure_named("Manifest", &Schema::Object(schema.schema.clone()))?;
    generator.emit()
}

struct TypeGenerator<'a> {
    root: &'a RootSchema,
    decls: HashMap<String, String>,
    order: Vec<String>,
}

impl<'a> TypeGenerator<'a> {
    fn new(root: &'a RootSchema) -> Self {
        Self {
            root,
            decls: HashMap::new(),
            order: Vec::new(),
        }
    }

    fn emit(&self) -> Result<String> {
        let mut out =
            String::from("// Auto-generated by cargo xtask schema-export. Do not edit.\n\n");
        for name in &self.order {
            if let Some(decl) = self.decls.get(name) {
                out.push_str(decl);
                if !decl.ends_with('\n') {
                    out.push('\n');
                }
                out.push('\n');
            }
        }
        if !out.ends_with('\n') {
            out.push('\n');
        }
        Ok(out)
    }

    fn ensure_named(&mut self, name: &str, schema: &Schema) -> Result<()> {
        if self.decls.contains_key(name) {
            return Ok(());
        }
        let decl = match schema {
            Schema::Bool(true) => format!("export type {name} = unknown;"),
            Schema::Bool(false) => format!("export type {name} = never;"),
            Schema::Object(obj) => self.render_named_object(name, obj)?,
        };
        self.decls.insert(name.to_string(), decl);
        self.order.push(name.to_string());
        Ok(())
    }

    fn render_named_object(&mut self, name: &str, obj: &SchemaObject) -> Result<String> {
        if let Some(reference) = &obj.reference {
            let ref_name = self.resolve_reference(reference)?;
            return Ok(format!("export type {name} = {ref_name};"));
        }

        if let Some(enum_values) = &obj.enum_values {
            let ty = self.render_enum(enum_values)?;
            return Ok(format!("export type {name} = {ty};"));
        }

        if let Some(subschemas) = &obj.subschemas {
            if let Some(one_of) = &subschemas.one_of {
                let union = self.render_union(one_of, 0)?;
                return Ok(format!("export type {name} = {union};"));
            }
            if let Some(any_of) = &subschemas.any_of {
                let union = self.render_union(any_of, 0)?;
                return Ok(format!("export type {name} = {union};"));
            }
            if let Some(all_of) = &subschemas.all_of {
                let mut parts = Vec::new();
                for schema in all_of {
                    parts.push(self.type_expression(schema, 0)?);
                }
                let ty = parts.join(" & ");
                return Ok(format!("export type {name} = {ty};"));
            }
        }

        if let Some(object) = &obj.object {
            let body = self.render_object_body(object, obj, 0)?;
            return Ok(format!("export interface {name} {body}"));
        }

        if let Some(array) = &obj.array {
            let ty = self.render_array(array, obj, 0)?;
            return Ok(format!("export type {name} = {ty};"));
        }

        if let Some(instance) = &obj.instance_type {
            let ty = self.render_instance_type(instance, obj, 0)?;
            return Ok(format!("export type {name} = {ty};"));
        }

        Ok(format!("export type {name} = unknown;"))
    }

    fn render_enum(&self, values: &[Value]) -> Result<String> {
        let mut parts = Vec::new();
        for value in values {
            let literal = match value {
                Value::String(s) => format!("{:?}", s),
                Value::Number(n) => n
                    .as_i64()
                    .map(|i| i.to_string())
                    .or_else(|| n.as_f64().map(|f| f.to_string()))
                    .context("unsupported numeric enum variant")?,
                Value::Bool(b) => b.to_string(),
                Value::Null => "null".to_string(),
                _ => bail!("unsupported enum literal in schema: {}", value),
            };
            parts.push(literal);
        }
        Ok(parts.join(" | "))
    }

    fn render_union(&mut self, schemas: &[Schema], indent: usize) -> Result<String> {
        let mut parts = Vec::new();
        for subschema in schemas {
            parts.push(self.type_expression(subschema, indent)?);
        }
        Ok(parts.join(" | "))
    }

    fn type_expression(&mut self, schema: &Schema, indent: usize) -> Result<String> {
        match schema {
            Schema::Bool(true) => Ok("unknown".into()),
            Schema::Bool(false) => Ok("never".into()),
            Schema::Object(obj) => self.type_from_object(obj, indent),
        }
    }

    fn type_from_object(&mut self, obj: &SchemaObject, indent: usize) -> Result<String> {
        if let Some(reference) = &obj.reference {
            let name = self.resolve_reference(reference)?;
            if let Some(def) = self.root.definitions.get(&name) {
                self.ensure_named(&name, def)?;
            }
            return Ok(name);
        }

        if let Some(enum_values) = &obj.enum_values {
            return self.render_enum(enum_values);
        }

        if let Some(subschemas) = &obj.subschemas {
            if let Some(one_of) = &subschemas.one_of {
                return self.render_union(one_of, indent);
            }
            if let Some(any_of) = &subschemas.any_of {
                return self.render_union(any_of, indent);
            }
            if let Some(all_of) = &subschemas.all_of {
                let mut parts = Vec::new();
                for schema in all_of {
                    parts.push(self.type_expression(schema, indent)?);
                }
                return Ok(parts.join(" & "));
            }
        }

        if let Some(object) = &obj.object {
            return self.render_object_body(object, obj, indent);
        }

        if let Some(array) = &obj.array {
            return self.render_array(array, obj, indent);
        }

        if let Some(instance) = &obj.instance_type {
            return self.render_instance_type(instance, obj, indent);
        }

        Ok("unknown".into())
    }

    fn render_object_body(
        &mut self,
        object: &ObjectValidation,
        obj: &SchemaObject,
        indent: usize,
    ) -> Result<String> {
        let mut lines = Vec::new();
        let mut required: BTreeSet<String> = object.required.iter().cloned().collect();

        for (name, property_schema) in &object.properties {
            let is_required = required.remove(name);
            let field_name = format_property_name(name);
            let ts_type = self.type_expression(property_schema, indent + 2)?;
            let optional = if is_required { "" } else { "?" };
            let line = format!(
                "{}{}{}: {};",
                indent_spaces(indent + 2),
                field_name,
                optional,
                ts_type
            );
            lines.push(line);
        }

        if let Some(additional) = &object.additional_properties {
            let ts_type = self.type_expression(additional, indent + 2)?;
            lines.push(format!(
                "{}[key: string]: {};",
                indent_spaces(indent + 2),
                ts_type
            ));
        }

        if let Some(metadata) = &obj.metadata {
            if let Some(desc) = &metadata.description {
                let comment = format_comment(desc, indent + 1);
                if !comment.is_empty() {
                    lines.insert(0, comment);
                }
            }
        }

        if lines.is_empty() {
            Ok("{}".into())
        } else {
            let inner = lines.join("\n");
            Ok(format!("{{\n{}\n{}}}", inner, indent_spaces(indent)))
        }
    }

    fn render_array(
        &mut self,
        array: &ArrayValidation,
        _obj: &SchemaObject,
        indent: usize,
    ) -> Result<String> {
        let item_type = match &array.items {
            Some(SingleOrVec::Single(schema)) => self.type_expression(schema, indent)?,
            Some(SingleOrVec::Vec(items)) => {
                let mut parts = Vec::new();
                for schema in items {
                    parts.push(self.type_expression(schema, indent)?);
                }
                parts.join(" | ")
            }
            None => "unknown".into(),
        };
        Ok(format!("Array<{}>", item_type))
    }

    fn render_instance_type(
        &mut self,
        instance: &SingleOrVec<InstanceType>,
        obj: &SchemaObject,
        indent: usize,
    ) -> Result<String> {
        match instance {
            SingleOrVec::Single(single) => self.render_single_instance(single, obj, indent),
            SingleOrVec::Vec(list) => {
                let mut parts = Vec::new();
                for item in list {
                    parts.push(self.render_single_instance(item, obj, indent)?);
                }
                Ok(parts.join(" | "))
            }
        }
    }

    fn render_single_instance(
        &mut self,
        instance: &InstanceType,
        obj: &SchemaObject,
        indent: usize,
    ) -> Result<String> {
        Ok(match instance {
            InstanceType::Boolean => "boolean".into(),
            InstanceType::Integer | InstanceType::Number => "number".into(),
            InstanceType::String => "string".into(),
            InstanceType::Null => "null".into(),
            InstanceType::Array => {
                if let Some(array) = &obj.array {
                    self.render_array(array, obj, indent)?
                } else {
                    "Array<unknown>".into()
                }
            }
            InstanceType::Object => {
                if let Some(object) = &obj.object {
                    self.render_object_body(object, obj, indent)?
                } else {
                    "{}".into()
                }
            }
        })
    }

    fn resolve_reference(&self, reference: &str) -> Result<String> {
        reference
            .strip_prefix("#/definitions/")
            .map(|s| s.to_string())
            .context(format!("unsupported schema reference: {reference}"))
    }
}

fn indent_spaces(level: usize) -> String {
    " ".repeat(level)
}

fn format_property_name(raw: &str) -> String {
    if raw
        .chars()
        .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
        && !raw.chars().next().unwrap_or('_').is_numeric()
    {
        raw.to_string()
    } else {
        format!("{:?}", raw)
    }
}

fn format_comment(desc: &str, indent: usize) -> String {
    if desc.trim().is_empty() {
        return String::new();
    }
    let lines: Vec<String> = desc
        .lines()
        .map(|line| format!("{}* {}", indent_spaces(indent), line.trim()))
        .collect();
    if lines.is_empty() {
        String::new()
    } else {
        format!(
            "{0}/**\n{1}\n{0}*/",
            indent_spaces(indent - 1),
            lines.join("\n")
        )
    }
}
