// Proto types generated by tonic-build in build.rs
// Include generated code from src/proto directory

pub mod onescluster {
    pub mod common {
        pub mod v1 {
            include!("onescluster.common.v1.rs");
        }
    }
    pub mod engine {
        pub mod v1 {
            include!("onescluster.engine.v1.rs");
        }
    }
    pub mod coordinator {
        pub mod v1 {
            include!("onescluster.coordinator.v1.rs");
        }
    }
}
