// Proto types generated by tonic-build in build.rs
// Include generated code from src/proto directory

// Allow clippy warnings for auto-generated code
#[allow(clippy::large_enum_variant)]
pub mod nacelle {
    pub mod common {
        pub mod v1 {
            include!("nacelle.common.v1.rs");
        }
    }
    pub mod engine {
        pub mod v1 {
            include!("nacelle.engine.v1.rs");
        }
    }
}
