// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchModelRequest {
    /// Logical identifier for the model (used for cache directory naming)
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    /// Source URL (HTTP/HTTPS)
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    /// Optional expected SHA-256 hex (lower/upper acceptable). Empty means "don't verify".
    #[prost(string, tag = "3")]
    pub expected_sha256: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchModelResponse {
    /// Absolute local path to the cached file (host path)
    #[prost(string, tag = "1")]
    pub local_path: ::prost::alloc::string::String,
    /// True if the file was already present and re-used.
    #[prost(bool, tag = "2")]
    pub cached: bool,
    /// Bytes downloaded in this call (0 if cached).
    #[prost(uint64, tag = "3")]
    pub bytes_downloaded: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRequest {
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
    /// If true, stream updates. If false, return current content and close.
    #[prost(bool, tag = "2")]
    pub follow: bool,
    /// Number of lines to return from the end (0 for all/default)
    #[prost(uint64, tag = "3")]
    pub tail_lines: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EngineLogEntry {
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    /// ISO8601
    #[prost(string, tag = "2")]
    pub timestamp: ::prost::alloc::string::String,
    /// "stdout" or "stderr"
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
}
/// Empty request message
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetResourcesRequest {}
/// Empty request message
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSystemStatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployRequest {
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
    /// Optional, can be derived from manifest
    #[prost(string, tag = "3")]
    pub oci_image: ::prost::alloc::string::String,
    /// Optional
    #[prost(string, tag = "4")]
    pub digest: ::prost::alloc::string::String,
    /// Raw signature bytes (Ed25519)
    #[prost(bytes = "vec", tag = "7")]
    pub manifest_signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "deploy_request::Manifest", tags = "2, 5, 6, 8")]
    pub manifest: ::core::option::Option<deploy_request::Manifest>,
}
/// Nested message and enum types in `DeployRequest`.
pub mod deploy_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Manifest {
        /// Legacy JSON support
        #[prost(bytes, tag = "2")]
        AdepJson(::prost::alloc::vec::Vec<u8>),
        /// TOML manifest content
        #[prost(string, tag = "5")]
        TomlContent(::prost::alloc::string::String),
        /// Normalized execution plan (protobuf)
        #[prost(message, tag = "6")]
        RunPlan(super::super::super::common::v1::RunPlan),
        /// Cap'n Proto SSOT manifest (preferred)
        #[prost(bytes, tag = "8")]
        CapnpManifest(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployResponse {
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// e.g., "<http://verification-capsule.local">
    #[prost(string, tag = "3")]
    pub local_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub failure_codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub failure_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopRequest {
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopResponse {
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceInfo {
    #[prost(uint64, tag = "1")]
    pub cpu_cores: u64,
    #[prost(uint64, tag = "2")]
    pub memory_bytes: u64,
    #[prost(uint64, tag = "3")]
    pub disk_bytes: u64,
    /// "cpu", "gpu", or "mock"
    #[prost(string, tag = "4")]
    pub backend_mode: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub vpn_ip: ::prost::alloc::string::String,
    /// name -> port
    #[prost(map = "string, uint32", tag = "6")]
    pub local_services: ::std::collections::HashMap<::prost::alloc::string::String, u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateRequest {
    #[prost(oneof = "validate_request::Manifest", tags = "1, 2")]
    pub manifest: ::core::option::Option<validate_request::Manifest>,
}
/// Nested message and enum types in `ValidateRequest`.
pub mod validate_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Manifest {
        /// Legacy JSON support (deprecated)
        #[prost(bytes, tag = "1")]
        AdepJson(::prost::alloc::vec::Vec<u8>),
        /// Cap'n Proto SSOT manifest (preferred)
        #[prost(bytes, tag = "2")]
        CapnpManifest(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResult {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemStatus {
    /// "cpu", "gpu", "mock"
    #[prost(string, tag = "1")]
    pub backend_mode: ::prost::alloc::string::String,
    /// Headscale IP
    #[prost(string, tag = "2")]
    pub vpn_ip: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub capsules: ::prost::alloc::vec::Vec<CapsuleInfo>,
    #[prost(message, optional, tag = "4")]
    pub resources: ::core::option::Option<ResourceUsage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapsuleInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// "running", "stopped", "failed"
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    /// e.g., "<http://app.local">
    #[prost(string, tag = "4")]
    pub local_url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub reserved_vram_bytes: u64,
    /// empty if none
    #[prost(string, tag = "6")]
    pub last_failure: ::prost::alloc::string::String,
    /// -1 if unknown
    #[prost(int32, tag = "7")]
    pub last_exit_code: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ResourceUsage {
    #[prost(uint64, tag = "1")]
    pub cpu_cores_total: u64,
    #[prost(uint64, tag = "2")]
    pub cpu_cores_used: u64,
    #[prost(uint64, tag = "3")]
    pub memory_bytes_total: u64,
    #[prost(uint64, tag = "4")]
    pub memory_bytes_used: u64,
    #[prost(uint64, tag = "5")]
    pub vram_bytes_total: u64,
    #[prost(uint64, tag = "6")]
    pub vram_bytes_used: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJobStatusRequest {
    /// Unique job identifier (typically capsule_id)
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJobStatusResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub capsule_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub capsule_version: ::prost::alloc::string::String,
    #[prost(enumeration = "JobPhase", tag = "4")]
    pub phase: i32,
    /// Empty if no error
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    /// -1 if not applicable
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    /// ISO8601
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
    /// ISO8601, empty if not started
    #[prost(string, tag = "8")]
    pub started_at: ::prost::alloc::string::String,
    /// ISO8601, empty if not finished
    #[prost(string, tag = "9")]
    pub finished_at: ::prost::alloc::string::String,
    /// 0 if still running or not started
    #[prost(uint64, tag = "10")]
    pub duration_secs: u64,
    #[prost(message, optional, tag = "11")]
    pub resource_usage: ::core::option::Option<JobResourceUsage>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JobResourceUsage {
    /// Total CPU time used
    #[prost(uint64, tag = "1")]
    pub cpu_time_ms: u64,
    /// Peak memory usage
    #[prost(uint64, tag = "2")]
    pub memory_peak_bytes: u64,
    /// Peak VRAM usage (if GPU job)
    #[prost(uint64, tag = "3")]
    pub vram_peak_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsRequest {
    /// Max jobs to return (default: 100)
    #[prost(uint32, tag = "1")]
    pub limit: u32,
    /// Filter by capsule name (optional)
    #[prost(string, tag = "2")]
    pub capsule_name: ::prost::alloc::string::String,
    /// Filter by phase (optional, 0 = all)
    #[prost(enumeration = "JobPhase", tag = "3")]
    pub phase_filter: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListJobsResponse {
    #[prost(message, repeated, tag = "1")]
    pub jobs: ::prost::alloc::vec::Vec<JobSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobSummary {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub capsule_name: ::prost::alloc::string::String,
    #[prost(enumeration = "JobPhase", tag = "3")]
    pub phase: i32,
    /// ISO8601
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    /// 0 if still running
    #[prost(uint64, tag = "5")]
    pub duration_secs: u64,
}
/// CancelJob - Request to cancel a running job
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelJobRequest {
    /// Job ID to cancel
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// If true, send SIGKILL instead of SIGTERM
    #[prost(bool, tag = "2")]
    pub force: bool,
}
/// CancelJob - Response after attempting cancellation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelJobResponse {
    /// True if cancellation was initiated
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Human-readable status message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Phase before cancellation attempt
    #[prost(enumeration = "JobPhase", tag = "3")]
    pub previous_phase: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobPhase {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Succeeded = 3,
    Failed = 4,
    Cancelled = 5,
}
impl JobPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_PHASE_UNSPECIFIED",
            Self::Pending => "JOB_PHASE_PENDING",
            Self::Running => "JOB_PHASE_RUNNING",
            Self::Succeeded => "JOB_PHASE_SUCCEEDED",
            Self::Failed => "JOB_PHASE_FAILED",
            Self::Cancelled => "JOB_PHASE_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_PHASE_PENDING" => Some(Self::Pending),
            "JOB_PHASE_RUNNING" => Some(Self::Running),
            "JOB_PHASE_SUCCEEDED" => Some(Self::Succeeded),
            "JOB_PHASE_FAILED" => Some(Self::Failed),
            "JOB_PHASE_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod engine_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct EngineClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EngineClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EngineClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EngineClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EngineClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn deploy_capsule(
            &mut self,
            request: impl tonic::IntoRequest<super::DeployRequest>,
        ) -> std::result::Result<tonic::Response<super::DeployResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/DeployCapsule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "DeployCapsule"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_capsule(
            &mut self,
            request: impl tonic::IntoRequest<super::StopRequest>,
        ) -> std::result::Result<tonic::Response<super::StopResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/StopCapsule",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "StopCapsule"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_resources(
            &mut self,
            request: impl tonic::IntoRequest<super::GetResourcesRequest>,
        ) -> std::result::Result<tonic::Response<super::ResourceInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/GetResources",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "GetResources"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_manifest(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidationResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/ValidateManifest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "ValidateManifest"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_system_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSystemStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::SystemStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/GetSystemStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "GetSystemStatus"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::LogRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::EngineLogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/StreamLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "StreamLogs"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Model prefetch/cache: download (if missing) to an allowlisted host path.
        pub async fn fetch_model(
            &mut self,
            request: impl tonic::IntoRequest<super::FetchModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FetchModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/FetchModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "FetchModel"));
            self.inner.unary(req, path, codec).await
        }
        /// Get job execution status (Phase 3: Coordinator integration)
        pub async fn get_job_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetJobStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJobStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/GetJobStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "GetJobStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// List recent jobs with optional filtering
        pub async fn list_jobs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListJobsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListJobsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/ListJobs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "ListJobs"));
            self.inner.unary(req, path, codec).await
        }
        /// Cancel a running job (Phase 6: Control Plane completion)
        pub async fn cancel_job(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelJobRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelJobResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nacelle.engine.v1.Engine/CancelJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nacelle.engine.v1.Engine", "CancelJob"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod engine_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EngineServer.
    #[async_trait]
    pub trait Engine: std::marker::Send + std::marker::Sync + 'static {
        async fn deploy_capsule(
            &self,
            request: tonic::Request<super::DeployRequest>,
        ) -> std::result::Result<tonic::Response<super::DeployResponse>, tonic::Status>;
        async fn stop_capsule(
            &self,
            request: tonic::Request<super::StopRequest>,
        ) -> std::result::Result<tonic::Response<super::StopResponse>, tonic::Status>;
        async fn get_resources(
            &self,
            request: tonic::Request<super::GetResourcesRequest>,
        ) -> std::result::Result<tonic::Response<super::ResourceInfo>, tonic::Status>;
        async fn validate_manifest(
            &self,
            request: tonic::Request<super::ValidateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidationResult>,
            tonic::Status,
        >;
        async fn get_system_status(
            &self,
            request: tonic::Request<super::GetSystemStatusRequest>,
        ) -> std::result::Result<tonic::Response<super::SystemStatus>, tonic::Status>;
        /// Server streaming response type for the StreamLogs method.
        type StreamLogsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::EngineLogEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn stream_logs(
            &self,
            request: tonic::Request<super::LogRequest>,
        ) -> std::result::Result<tonic::Response<Self::StreamLogsStream>, tonic::Status>;
        /// Model prefetch/cache: download (if missing) to an allowlisted host path.
        async fn fetch_model(
            &self,
            request: tonic::Request<super::FetchModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FetchModelResponse>,
            tonic::Status,
        >;
        /// Get job execution status (Phase 3: Coordinator integration)
        async fn get_job_status(
            &self,
            request: tonic::Request<super::GetJobStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJobStatusResponse>,
            tonic::Status,
        >;
        /// List recent jobs with optional filtering
        async fn list_jobs(
            &self,
            request: tonic::Request<super::ListJobsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListJobsResponse>,
            tonic::Status,
        >;
        /// Cancel a running job (Phase 6: Control Plane completion)
        async fn cancel_job(
            &self,
            request: tonic::Request<super::CancelJobRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelJobResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct EngineServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EngineServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EngineServer<T>
    where
        T: Engine,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nacelle.engine.v1.Engine/DeployCapsule" => {
                    #[allow(non_camel_case_types)]
                    struct DeployCapsuleSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::DeployRequest>
                    for DeployCapsuleSvc<T> {
                        type Response = super::DeployResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeployRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::deploy_capsule(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeployCapsuleSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/StopCapsule" => {
                    #[allow(non_camel_case_types)]
                    struct StopCapsuleSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::StopRequest>
                    for StopCapsuleSvc<T> {
                        type Response = super::StopResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::stop_capsule(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopCapsuleSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/GetResources" => {
                    #[allow(non_camel_case_types)]
                    struct GetResourcesSvc<T: Engine>(pub Arc<T>);
                    impl<
                        T: Engine,
                    > tonic::server::UnaryService<super::GetResourcesRequest>
                    for GetResourcesSvc<T> {
                        type Response = super::ResourceInfo;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetResourcesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::get_resources(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetResourcesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/ValidateManifest" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateManifestSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::ValidateRequest>
                    for ValidateManifestSvc<T> {
                        type Response = super::ValidationResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ValidateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::validate_manifest(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ValidateManifestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/GetSystemStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetSystemStatusSvc<T: Engine>(pub Arc<T>);
                    impl<
                        T: Engine,
                    > tonic::server::UnaryService<super::GetSystemStatusRequest>
                    for GetSystemStatusSvc<T> {
                        type Response = super::SystemStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSystemStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::get_system_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSystemStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/StreamLogs" => {
                    #[allow(non_camel_case_types)]
                    struct StreamLogsSvc<T: Engine>(pub Arc<T>);
                    impl<
                        T: Engine,
                    > tonic::server::ServerStreamingService<super::LogRequest>
                    for StreamLogsSvc<T> {
                        type Response = super::EngineLogEntry;
                        type ResponseStream = T::StreamLogsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::stream_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamLogsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/FetchModel" => {
                    #[allow(non_camel_case_types)]
                    struct FetchModelSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::FetchModelRequest>
                    for FetchModelSvc<T> {
                        type Response = super::FetchModelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FetchModelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::fetch_model(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FetchModelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/GetJobStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetJobStatusSvc<T: Engine>(pub Arc<T>);
                    impl<
                        T: Engine,
                    > tonic::server::UnaryService<super::GetJobStatusRequest>
                    for GetJobStatusSvc<T> {
                        type Response = super::GetJobStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetJobStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::get_job_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetJobStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/ListJobs" => {
                    #[allow(non_camel_case_types)]
                    struct ListJobsSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::ListJobsRequest>
                    for ListJobsSvc<T> {
                        type Response = super::ListJobsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListJobsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::list_jobs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListJobsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nacelle.engine.v1.Engine/CancelJob" => {
                    #[allow(non_camel_case_types)]
                    struct CancelJobSvc<T: Engine>(pub Arc<T>);
                    impl<T: Engine> tonic::server::UnaryService<super::CancelJobRequest>
                    for CancelJobSvc<T> {
                        type Response = super::CancelJobResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelJobRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Engine>::cancel_job(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelJobSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EngineServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nacelle.engine.v1.Engine";
    impl<T> tonic::server::NamedService for EngineServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
