// This file is @generated by prost-build.
/// RunPlan v0: normalized execution plan (Phase 2)
/// Shared between coordinator.proto and engine.proto
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunPlan {
    /// Traceability
    #[prost(string, tag = "1")]
    pub capsule_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// Resources
    ///
    /// optional
    #[prost(uint32, tag = "20")]
    pub cpu_cores: u32,
    /// optional
    #[prost(uint64, tag = "21")]
    pub memory_bytes: u64,
    /// optional, e.g., "none" | "cuda:L4:1"
    #[prost(string, tag = "22")]
    pub gpu_profile: ::prost::alloc::string::String,
    /// Network
    ///
    /// optional CIDR/host list
    #[prost(string, repeated, tag = "30")]
    pub egress_allowlist: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Runtime selection
    #[prost(oneof = "run_plan::Runtime", tags = "10, 11, 12, 13, 14")]
    pub runtime: ::core::option::Option<run_plan::Runtime>,
}
/// Nested message and enum types in `RunPlan`.
pub mod run_plan {
    /// Runtime selection
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Runtime {
        #[prost(message, tag = "10")]
        Docker(super::DockerRuntime),
        #[prost(message, tag = "11")]
        Native(super::NativeRuntime),
        /// Optional: enable only if supported
        #[prost(message, tag = "12")]
        PythonUv(super::PythonUvRuntime),
        /// WebAssembly Component Model
        #[prost(message, tag = "13")]
        Wasm(super::WasmRuntime),
        /// Generic Source Runtime (any language)
        #[prost(message, tag = "14")]
        Source(super::SourceRuntime),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DockerRuntime {
    #[prost(string, tag = "1")]
    pub image: ::prost::alloc::string::String,
    /// optional
    #[prost(string, tag = "2")]
    pub digest: ::prost::alloc::string::String,
    /// entrypoint/command
    #[prost(string, repeated, tag = "3")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// optional
    #[prost(string, tag = "5")]
    pub working_dir: ::prost::alloc::string::String,
    /// optional
    #[prost(string, tag = "6")]
    pub user: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "7")]
    pub ports: ::prost::alloc::vec::Vec<Port>,
    #[prost(message, repeated, tag = "8")]
    pub mounts: ::prost::alloc::vec::Vec<Mount>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NativeRuntime {
    #[prost(string, tag = "1")]
    pub binary_path: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "4")]
    pub working_dir: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PythonUvRuntime {
    #[prost(string, tag = "1")]
    pub entrypoint: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "4")]
    pub working_dir: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub ports: ::prost::alloc::vec::Vec<Port>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmRuntime {
    /// Path to .wasm component file
    #[prost(string, tag = "1")]
    pub component: ::prost::alloc::string::String,
    /// Source directory
    #[prost(string, tag = "2")]
    pub working_dir: ::prost::alloc::string::String,
    /// Optional CLI arguments
    #[prost(string, repeated, tag = "3")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional environment variables
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Generic Source Runtime: Execute any language runtime from host
/// Supports explicit command specification via `cmd` field
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SourceRuntime {
    /// Language hint (python, ruby, node, etc.)
    #[prost(string, tag = "1")]
    pub language: ::prost::alloc::string::String,
    /// Entry point file (e.g., "main.py", "app.rb")
    #[prost(string, tag = "2")]
    pub entrypoint: ::prost::alloc::string::String,
    /// Explicit command (e.g., \["ruby", "app.rb"\])
    #[prost(string, repeated, tag = "3")]
    pub cmd: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Additional arguments
    #[prost(string, repeated, tag = "4")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Environment variables
    #[prost(map = "string, string", tag = "5")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Source directory
    #[prost(string, tag = "6")]
    pub working_dir: ::prost::alloc::string::String,
    /// Enable relaxed security for development
    #[prost(bool, tag = "7")]
    pub dev_mode: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Port {
    #[prost(uint32, tag = "1")]
    pub container_port: u32,
    /// optional
    #[prost(uint32, tag = "2")]
    pub host_port: u32,
    /// optional
    #[prost(string, tag = "3")]
    pub protocol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mount {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub readonly: bool,
}
