[target.aarch64-unknown-linux-gnu]
linker = "scripts/aarch64-linux-gnu-cc.sh"

[env]
CC_aarch64_unknown_linux_gnu = { value = "scripts/aarch64-linux-gnu-cc.sh", relative = true }
"CC_aarch64-unknown-linux-gnu" = { value = "scripts/aarch64-linux-gnu-cc.sh", relative = true }
