use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;

use async_trait::async_trait;
use tokio::process::Command;
use tracing::{info, warn, error};

use crate::artifact::ArtifactManager;
use crate::process_supervisor::ProcessSupervisor;
use crate::runtime::traits::Runtime;
use crate::runtime::{LaunchRequest, LaunchResult, RuntimeError};

/// Native runtime that executes binaries directly on the host.
#[derive(Debug)]
pub struct NativeRuntime {
    artifact_manager: Option<Arc<ArtifactManager>>,
    process_supervisor: Option<Arc<ProcessSupervisor>>,
    egress_proxy_port: Option<u16>,
}

impl NativeRuntime {
    pub fn new(
        artifact_manager: Option<Arc<ArtifactManager>>,
        process_supervisor: Option<Arc<ProcessSupervisor>>,
        egress_proxy_port: Option<u16>,
    ) -> Self {
        Self {
            artifact_manager,
            process_supervisor,
            egress_proxy_port,
        }
    }
}

#[async_trait]
impl Runtime for NativeRuntime {
    async fn launch(&self, request: LaunchRequest<'_>) -> Result<LaunchResult, RuntimeError> {
        let native_config = request.spec.process().as_ref().and_then(|_process| {
            // In a real implementation, we would parse the spec to find native config.
            // For now, we assume the caller has validated this or we extract from env/args.
            // However, the current `LaunchRequest` passes `Spec`.
            // The `AdepManifest` had `native` config, but `LaunchRequest` uses OCI `Spec`.
            // We need to bridge this gap.
            //
            // For this refactoring, we will assume the `args` in `Spec` contain the command to run.
            // But wait, `capsule_manager.rs` used `manifest.compute.native`.
            // We need to ensure `LaunchRequest` has enough info.
            // `LaunchRequest` has `manifest_json`. We can parse it again or pass `AdepManifest`.
            //
            // Let's parse `manifest_json` to get `native` config if needed, or rely on `Spec` args.
            // The `capsule_manager.rs` logic was:
            // 1. Ensure runtime (artifact)
            // 2. Expand args
            // 3. Spawn process
            
            // Let's try to extract the command from `Spec` args for now, 
            // but we also need the `runtime_id` for artifact manager.
            // The `Spec` generated by `spec_builder.rs` should ideally contain the resolved path if possible,
            // OR we need to do artifact resolution here.
            
            // Re-parsing manifest from JSON seems safest to preserve exact behavior for now.
            if let Some(json) = request.manifest_json {
                 let manifest: crate::adep::AdepManifest = serde_json::from_str(json).ok()?;
                 manifest.compute.native
            } else {
                None
            }
        }).ok_or_else(|| RuntimeError::InvalidConfig("Missing native configuration in manifest".to_string()))?;

        let (runtime_id, version) = if let Some(at_pos) = native_config.runtime.find('@') {
            let (id, ver) = native_config.runtime.split_at(at_pos);
            (id, &ver[1..])
        } else {
            (native_config.runtime.as_str(), "latest")
        };

        info!("Ensuring runtime {}@{}", runtime_id, version);

        // Special handling for built-in runtimes (mlx, llama, vllm)
        let binary_path = match runtime_id {
            "mlx-mock" => {
                info!("Using mock MLX runtime (shell pass-through)");
                PathBuf::from("/usr/bin/env")
            }
            "mlx" => {
                // MLX runtime uses start.sh in ~/.gumball/runtimes/mlx
                let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
                let mlx_runtime_path = PathBuf::from(&home)
                    .join(".gumball")
                    .join("runtimes")
                    .join("mlx")
                    .join("start.sh");
                
                // Fallback to development path
                if mlx_runtime_path.exists() {
                    info!("Using MLX runtime at: {:?}", mlx_runtime_path);
                    mlx_runtime_path
                } else {
                    // Try project path for development
                    let dev_path = std::env::current_dir()
                        .unwrap_or_default()
                        .parent()
                        .map(|p| p.join("desktop/mlx-runtime/start.sh"))
                        .unwrap_or_default();
                    if dev_path.exists() {
                        info!("Using MLX dev runtime at: {:?}", dev_path);
                        dev_path
                    } else {
                        return Err(RuntimeError::InvalidConfig(
                            format!("MLX runtime not found. Expected at {:?} or {:?}", mlx_runtime_path, dev_path)
                        ));
                    }
                }
            }
            _ if std::path::Path::new(runtime_id).is_absolute() && std::path::Path::new(runtime_id).exists() => {
                // Check if runtime is an absolute path to an existing file
                info!("Using direct path: {}", runtime_id);
                std::path::PathBuf::from(runtime_id)
            }
            _ => {
                // Use artifact manager for other runtimes
                if let Some(am) = &self.artifact_manager {
                    am.ensure_runtime(runtime_id, version, None)
                        .await
                        .map_err(|e| RuntimeError::InvalidConfig(format!("Failed to ensure runtime: {}", e)))?
                } else {
                    return Err(RuntimeError::InvalidConfig("ArtifactManager not configured and runtime is not a direct path".to_string()));
                }
            }
        };

        // Variable expansion (e.g. ${PORT})
        // We need the allocated port. `LaunchRequest` doesn't have it explicitly?
        // `capsule_manager.rs` passed `p` (port).
        // We might need to extend `LaunchRequest` or `Spec` env vars.
        // OCI Spec `process.env` should contain `PORT=...`.
        // Let's assume `PORT` is in env vars of the `Spec`.
        
        let mut env_vars = std::collections::HashMap::new();
        if let Some(process) = request.spec.process() {
            if let Some(env) = process.env() {
                for e in env {
                    if let Some((k, v)) = e.split_once('=') {
                        // Filter out problematic empty HOST variable
                        if k == "HOST" && (v.is_empty() || v.trim().is_empty()) {
                            warn!("Filtering out empty/whitespace HOST environment variable");
                            continue;
                        }
                        env_vars.insert(k.to_string(), v.to_string());
                    }
                }
            }
        }
        
        info!("[DEBUG] Native runtime env_vars: {:?}", env_vars);
        
        if let Some(host_val) = env_vars.get("HOST") {
            warn!("[DEBUG] HOST environment variable detected: '{}'", host_val);
            if host_val.is_empty() {
                error!("[DEBUG] HOST is empty string - this will cause socket errors!");
            }
        } else {
            info!("[DEBUG] HOST environment variable not present (good)");
        }

        let port = env_vars.get("PORT").cloned().unwrap_or_else(|| "0".to_string());
        info!("[DEBUG] Native runtime using PORT={}", port);
        
        // Define GUMBALL_MODELS_DIR
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
        let models_dir = PathBuf::from(&home).join(".gumball").join("models");
        let models_dir_str = models_dir.to_string_lossy();

        let args: Vec<String> = native_config.args.iter().map(|arg| {
            arg.replace("${PORT}", &port)
               .replace("${GUMBALL_MODELS_DIR}", &models_dir_str)
        }).collect();

        // Create log file
        let log_dir = std::env::temp_dir().join("capsuled").join("logs");
        std::fs::create_dir_all(&log_dir).map_err(|e| RuntimeError::Io { path: log_dir.clone(), source: e })?;
        let log_path_buf = log_dir.join(format!("{}.log", request.workload_id));
        let log_file = std::fs::File::create(&log_path_buf).map_err(|e| RuntimeError::Io { path: log_path_buf.clone(), source: e })?;
        
        let (stdout, stderr) = {
            let stderr = log_file.try_clone().ok().map(Stdio::from).unwrap_or(Stdio::null());
            (Stdio::from(log_file), stderr)
        };

        let mut cmd = Command::new(&binary_path);
        cmd.args(&args)
           .stdout(stdout)
           .stderr(stderr)
           .envs(&env_vars); // Apply env vars from Spec

        if let Some(proxy_port) = self.egress_proxy_port {
            let proxy_url = if let Some(token) = env_vars.get(crate::security::ENV_KEY_EGRESS_TOKEN) {
                format!(
                    "http://{}:{}@127.0.0.1:{}",
                    request.workload_id, token, proxy_port
                )
            } else {
                format!("http://127.0.0.1:{}", proxy_port)
            };
            cmd.env("HTTP_PROXY", &proxy_url)
               .env("HTTPS_PROXY", &proxy_url)
               .env("ALL_PROXY", &proxy_url);
        }

        match cmd.spawn() {
            Ok(child) => {
                let pid = child.id().ok_or_else(|| RuntimeError::CommandFailure { 
                    operation: "spawn".to_string(), 
                    exit_code: None, 
                    stderr: "Failed to get PID".to_string() 
                })?;
                
                info!("Native runtime started with PID {}", pid);

                // Write PID file
                let state_dir = std::env::temp_dir().join("capsuled").join("state");
                std::fs::create_dir_all(&state_dir).map_err(|e| RuntimeError::Io { path: state_dir.clone(), source: e })?;
                let pid_file = state_dir.join(format!("{}.pid", request.workload_id));
                std::fs::write(&pid_file, pid.to_string()).map_err(|e| RuntimeError::Io { path: pid_file.clone(), source: e })?;

                if let Some(_supervisor) = &self.process_supervisor {
                    // TODO: Integrate with ProcessSupervisor if needed
                }
                
                Ok(LaunchResult {
                    pid,
                    bundle_path: PathBuf::from("/"), // Not applicable for native
                    log_path: log_path_buf,
                })
            }
            Err(e) => Err(RuntimeError::CommandExecution {
                operation: "spawn".to_string(),
                source: e,
            }),
        }
    }

    async fn stop(&self, workload_id: &str) -> Result<(), RuntimeError> {
        let pid_file = std::env::temp_dir().join("capsuled").join("state").join(format!("{}.pid", workload_id));
        if pid_file.exists() {
            if let Ok(content) = std::fs::read_to_string(&pid_file) {
                if let Ok(pid) = content.trim().parse::<i32>() {
                     use nix::sys::signal::{self, Signal};
                     use nix::unistd::Pid;

                     info!("Stopping native process PID {}", pid);
                     match signal::kill(Pid::from_raw(pid), Signal::SIGTERM) {
                         Ok(_) => {},
                         Err(e) => warn!("Failed to stop native process {}: {}", pid, e),
                     }
                }
            }
            // Remove PID file
            let _ = std::fs::remove_file(pid_file);
        } else {
            warn!("No PID file found for workload {}", workload_id);
        }
        Ok(())
    }

    fn get_log_path(&self, workload_id: &str) -> Option<PathBuf> {
        let log_dir = std::env::temp_dir().join("capsuled").join("logs");
        Some(log_dir.join(format!("{}.log", workload_id)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artifact::manager::{ArtifactConfig, ArtifactManager};
    use std::os::unix::fs::PermissionsExt;
    use std::time::Duration;
    use tokio::time::sleep;

    async fn create_mock_artifact_manager(temp_dir: &std::path::Path) -> Arc<ArtifactManager> {
        let cache_path = temp_dir.join("cache");
        std::fs::create_dir_all(&cache_path).unwrap();

        // Determine platform string to match ArtifactManager logic
        let platform = if cfg!(target_os = "macos") {
            if cfg!(target_arch = "aarch64") { "mac-arm64" } else { "mac-x64" }
        } else {
            "linux-x64"
        };

        // Create mock runtime: "test-runtime" version "1.0"
        let runtime_dir = cache_path.join("test-runtime").join("1.0").join(platform);
        std::fs::create_dir_all(&runtime_dir).unwrap();

        // Create a dummy binary that sleeps
        let bin_path = runtime_dir.join("bin");
        std::fs::create_dir_all(&bin_path).unwrap();
        let binary = bin_path.join("run");
        
        let script = r#"#!/bin/sh
        # Echo PID to stdout for verification if needed, but NativeRuntime captures it from spawn
        echo "Mock Runtime Started"
        # Sleep to keep process alive for stop test
        sleep 10
        "#;
        std::fs::write(&binary, script).unwrap();
        std::fs::set_permissions(&binary, std::fs::Permissions::from_mode(0o755)).unwrap();

        // Write .binary_path marker
        std::fs::write(runtime_dir.join(".binary_path"), "bin/run").unwrap();

        let config = ArtifactConfig {
            registry_url: "http://localhost".to_string(), // Won't be used due to cache hit
            cache_path,
        };

        Arc::new(ArtifactManager::new(config).await.unwrap())
    }

    #[tokio::test]
    async fn test_native_runtime_launch_and_stop() {
        let temp_dir = tempfile::tempdir().unwrap();
        let artifact_manager = create_mock_artifact_manager(temp_dir.path()).await;
        
        let runtime = NativeRuntime::new(Some(artifact_manager), None, None);

        // Create a fake manifest JSON
        let manifest_json = r#"{
            "name": "test-workload",
            "compute": {
                "image": "ignore",
                "native": {
                    "runtime": "test-runtime@1.0",
                    "args": ["arg1"]
                }
            }
        }"#;

        // Mock Spec
        let spec = oci_spec::runtime::Spec::default();

        let request = LaunchRequest {
            workload_id: "test-workload",
            spec: &spec,
            manifest_json: Some(manifest_json),
        };

        // 1. Test Launch
        let result = runtime.launch(request).await.expect("Launch failed");
        assert!(result.pid > 0);
        
        // Verify PID file exists
        let pid_file = std::env::temp_dir().join("capsuled").join("state").join("test-workload.pid");
        assert!(pid_file.exists());
        let pid_content = std::fs::read_to_string(&pid_file).unwrap();
        assert_eq!(pid_content.trim(), result.pid.to_string());

        // Verify process is running (simple check)
        // In Rust, we can't easily check if PID exists without sending signal 0, 
        // but we know we just spawned it and it sleeps for 10s.

        // 2. Test Stop
        runtime.stop("test-workload").await.expect("Stop failed");

        // Verify PID file is gone
        // Wait a bit for file system?
        sleep(Duration::from_millis(100)).await;
        assert!(!pid_file.exists());

        // Verify process is gone? 
        // We can try to kill it again and expect failure, or check /proc (linux only).
        // For now, assuming `kill` command worked if it didn't error.
    }
}
