// Generated by tonic_build - do not edit manually

pub mod onescluster {
    pub mod coordinator {
        pub mod v1 {
            include!("onescluster.coordinator.v1.rs");
        }
    }

    pub mod engine {
        pub mod v1 {
            include!("onescluster.engine.v1.rs");
        }
    }
}
