// This file is @generated by prost-build.
/// Report submitted by Agent containing current hardware + workload state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusReportRequest {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<RigStatus>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusReportResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Agent state snapshot (source of truth for reconciliation)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RigStatus {
    /// Unique Rig identifier (hostname)
    #[prost(string, tag = "1")]
    pub rig_id: ::prost::alloc::string::String,
    /// Hardware metrics (VRAM, drivers, GPUs)
    #[prost(message, optional, tag = "2")]
    pub hardware: ::core::option::Option<HardwareState>,
    /// Workloads currently running on Agent
    #[prost(message, repeated, tag = "3")]
    pub running_workloads: ::prost::alloc::vec::Vec<WorkloadStatus>,
    /// Scheduling taints advertised by Agent
    #[prost(message, repeated, tag = "4")]
    pub taints: ::prost::alloc::vec::Vec<Taint>,
    /// Timestamp of this report (epoch seconds)
    #[prost(uint64, tag = "5")]
    pub reported_at_unix_seconds: u64,
    /// Whether this is mock data (for testing)
    #[prost(bool, tag = "6")]
    pub is_mock: bool,
}
/// Hardware snapshot for a Rig
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HardwareState {
    /// List of GPUs on this Rig
    #[prost(message, repeated, tag = "1")]
    pub gpus: ::prost::alloc::vec::Vec<GpuInfo>,
    /// System CUDA version (e.g., "12.2")
    #[prost(string, tag = "2")]
    pub system_cuda_version: ::prost::alloc::string::String,
    /// NVIDIA driver version (e.g., "525.60.11")
    #[prost(string, tag = "3")]
    pub system_driver_version: ::prost::alloc::string::String,
    /// Sum of VRAM across all GPUs
    #[prost(uint64, tag = "4")]
    pub total_vram_bytes: u64,
    /// VRAM currently consumed by running workloads
    #[prost(uint64, tag = "5")]
    pub used_vram_bytes: u64,
}
/// GPU information (maps to Rust GpuInfo)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GpuInfo {
    /// GPU index (0-based)
    #[prost(uint32, tag = "1")]
    pub index: u32,
    /// GPU name (e.g., "NVIDIA GeForce RTX 4090")
    #[prost(string, tag = "2")]
    pub device_name: ::prost::alloc::string::String,
    /// Total VRAM in bytes
    #[prost(uint64, tag = "3")]
    pub vram_total_bytes: u64,
    /// CUDA compute capability (e.g., "8.9")
    #[prost(string, tag = "4")]
    pub cuda_compute_capability: ::prost::alloc::string::String,
    /// Currently available VRAM (optional)
    #[prost(uint64, tag = "5")]
    pub vram_available_bytes: u64,
}
/// Workload instance currently running on the Rig
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkloadStatus {
    /// Unique workload identifier
    #[prost(string, tag = "1")]
    pub workload_id: ::prost::alloc::string::String,
    /// Human-friendly workload name (optional)
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// VRAM reserved by this workload
    #[prost(uint64, tag = "3")]
    pub reserved_vram_bytes: u64,
    /// Observed execution phase
    #[prost(enumeration = "WorkloadPhase", tag = "4")]
    pub phase: i32,
    /// Process ID of the container (0 = unknown)
    #[prost(uint64, tag = "5")]
    pub pid: u64,
    /// VRAM measured in bytes (fallback to reserved)
    #[prost(uint64, tag = "6")]
    pub observed_vram_bytes: u64,
}
/// Node-level taints advertised for scheduling decisions
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Taint {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(enumeration = "TaintEffect", tag = "3")]
    pub effect: i32,
}
/// Request to deploy a workload (Coordinator → Agent)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployWorkloadRequest {
    /// Unique workload identifier
    #[prost(string, tag = "1")]
    pub workload_id: ::prost::alloc::string::String,
    /// Strongly typed adep manifest
    #[prost(message, optional, tag = "2")]
    pub manifest: ::core::option::Option<AdePManifest>,
    /// Original JSON payload (for compatibility)
    #[prost(string, tag = "3")]
    pub manifest_json: ::prost::alloc::string::String,
}
/// Response to deploy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeployWorkloadResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Success message or error details
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Request to stop a workload (Coordinator → Agent)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopWorkloadRequest {
    #[prost(string, tag = "1")]
    pub workload_id: ::prost::alloc::string::String,
}
/// Response to stop request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopWorkloadResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Strict schema for adep.json manifest
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdePManifest {
    /// Workload name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Scheduling preferences/constraints
    #[prost(message, optional, tag = "2")]
    pub scheduling: ::core::option::Option<SchedulingConfig>,
    /// Container execution parameters
    #[prost(message, optional, tag = "3")]
    pub compute: ::core::option::Option<ComputeConfig>,
    /// Volume mounts
    #[prost(message, repeated, tag = "4")]
    pub volumes: ::prost::alloc::vec::Vec<Volume>,
    /// Arbitrary metadata for future use
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SchedulingConfig {
    /// GPU requirements
    #[prost(message, optional, tag = "1")]
    pub gpu: ::core::option::Option<GpuConstraints>,
    /// Scheduling strategy hint (e.g., "best_fit")
    #[prost(string, tag = "2")]
    pub strategy: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GpuConstraints {
    /// Minimum VRAM requirement (GB)
    #[prost(uint64, tag = "1")]
    pub vram_min_gb: u64,
    /// Minimum CUDA version requirement
    #[prost(string, tag = "2")]
    pub cuda_version_min: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComputeConfig {
    /// OCI image reference
    #[prost(string, tag = "1")]
    pub image: ::prost::alloc::string::String,
    /// Container args (entrypoint + args)
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Environment variables key/value
    #[prost(map = "string, string", tag = "3")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Volume {
    /// Mount type (e.g., "bind")
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    /// Host path
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    /// Container path
    #[prost(string, tag = "3")]
    pub destination: ::prost::alloc::string::String,
    /// Read-only flag
    #[prost(bool, tag = "4")]
    pub readonly: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkloadPhase {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Failed = 3,
    Succeeded = 4,
}
impl WorkloadPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            WorkloadPhase::Unspecified => "WORKLOAD_PHASE_UNSPECIFIED",
            WorkloadPhase::Pending => "WORKLOAD_PHASE_PENDING",
            WorkloadPhase::Running => "WORKLOAD_PHASE_RUNNING",
            WorkloadPhase::Failed => "WORKLOAD_PHASE_FAILED",
            WorkloadPhase::Succeeded => "WORKLOAD_PHASE_SUCCEEDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORKLOAD_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "WORKLOAD_PHASE_PENDING" => Some(Self::Pending),
            "WORKLOAD_PHASE_RUNNING" => Some(Self::Running),
            "WORKLOAD_PHASE_FAILED" => Some(Self::Failed),
            "WORKLOAD_PHASE_SUCCEEDED" => Some(Self::Succeeded),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaintEffect {
    Unspecified = 0,
    NoSchedule = 1,
    PreferNoSchedule = 2,
}
impl TaintEffect {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TaintEffect::Unspecified => "TAINT_EFFECT_UNSPECIFIED",
            TaintEffect::NoSchedule => "TAINT_EFFECT_NO_SCHEDULE",
            TaintEffect::PreferNoSchedule => "TAINT_EFFECT_PREFER_NO_SCHEDULE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TAINT_EFFECT_UNSPECIFIED" => Some(Self::Unspecified),
            "TAINT_EFFECT_NO_SCHEDULE" => Some(Self::NoSchedule),
            "TAINT_EFFECT_PREFER_NO_SCHEDULE" => Some(Self::PreferNoSchedule),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod coordinator_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Coordinator service - handles communication FROM Agents TO Coordinator
    #[derive(Debug, Clone)]
    pub struct CoordinatorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CoordinatorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CoordinatorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CoordinatorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            CoordinatorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Agent reports its observed state (hardware + running workloads)
        pub async fn report_status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusReportRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StatusReportResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/onescluster.coordinator.v1.CoordinatorService/ReportStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "onescluster.coordinator.v1.CoordinatorService",
                        "ReportStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod agent_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Agent service - handles communication FROM Coordinator TO Agents
    #[derive(Debug, Clone)]
    pub struct AgentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AgentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AgentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AgentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            AgentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Coordinator instructs Agent to deploy a workload
        pub async fn deploy_workload(
            &mut self,
            request: impl tonic::IntoRequest<super::DeployWorkloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeployWorkloadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/onescluster.coordinator.v1.AgentService/DeployWorkload",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "onescluster.coordinator.v1.AgentService",
                        "DeployWorkload",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Coordinator instructs Agent to stop a workload
        pub async fn stop_workload(
            &mut self,
            request: impl tonic::IntoRequest<super::StopWorkloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopWorkloadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/onescluster.coordinator.v1.AgentService/StopWorkload",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "onescluster.coordinator.v1.AgentService",
                        "StopWorkload",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod coordinator_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CoordinatorServiceServer.
    #[async_trait]
    pub trait CoordinatorService: Send + Sync + 'static {
        /// Agent reports its observed state (hardware + running workloads)
        async fn report_status(
            &self,
            request: tonic::Request<super::StatusReportRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StatusReportResponse>,
            tonic::Status,
        >;
    }
    /// Coordinator service - handles communication FROM Agents TO Coordinator
    #[derive(Debug)]
    pub struct CoordinatorServiceServer<T: CoordinatorService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: CoordinatorService> CoordinatorServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CoordinatorServiceServer<T>
    where
        T: CoordinatorService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/onescluster.coordinator.v1.CoordinatorService/ReportStatus" => {
                    #[allow(non_camel_case_types)]
                    struct ReportStatusSvc<T: CoordinatorService>(pub Arc<T>);
                    impl<
                        T: CoordinatorService,
                    > tonic::server::UnaryService<super::StatusReportRequest>
                    for ReportStatusSvc<T> {
                        type Response = super::StatusReportResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatusReportRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CoordinatorService>::report_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ReportStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: CoordinatorService> Clone for CoordinatorServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: CoordinatorService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: CoordinatorService> tonic::server::NamedService
    for CoordinatorServiceServer<T> {
        const NAME: &'static str = "onescluster.coordinator.v1.CoordinatorService";
    }
}
/// Generated server implementations.
pub mod agent_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AgentServiceServer.
    #[async_trait]
    pub trait AgentService: Send + Sync + 'static {
        /// Coordinator instructs Agent to deploy a workload
        async fn deploy_workload(
            &self,
            request: tonic::Request<super::DeployWorkloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeployWorkloadResponse>,
            tonic::Status,
        >;
        /// Coordinator instructs Agent to stop a workload
        async fn stop_workload(
            &self,
            request: tonic::Request<super::StopWorkloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopWorkloadResponse>,
            tonic::Status,
        >;
    }
    /// Agent service - handles communication FROM Coordinator TO Agents
    #[derive(Debug)]
    pub struct AgentServiceServer<T: AgentService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: AgentService> AgentServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AgentServiceServer<T>
    where
        T: AgentService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/onescluster.coordinator.v1.AgentService/DeployWorkload" => {
                    #[allow(non_camel_case_types)]
                    struct DeployWorkloadSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::DeployWorkloadRequest>
                    for DeployWorkloadSvc<T> {
                        type Response = super::DeployWorkloadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeployWorkloadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::deploy_workload(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DeployWorkloadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/onescluster.coordinator.v1.AgentService/StopWorkload" => {
                    #[allow(non_camel_case_types)]
                    struct StopWorkloadSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::StopWorkloadRequest>
                    for StopWorkloadSvc<T> {
                        type Response = super::StopWorkloadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopWorkloadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::stop_workload(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StopWorkloadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: AgentService> Clone for AgentServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: AgentService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: AgentService> tonic::server::NamedService for AgentServiceServer<T> {
        const NAME: &'static str = "onescluster.coordinator.v1.AgentService";
    }
}
