//! Cap'n Proto round-trip test for CapsuleManifest
//! This test verifies that Cap'n Proto bytes generated by Go can be correctly
//! parsed by Rust Engine code.

use crate::capnp_to_manifest::capsule_capnp::{
    capsule_manifest, CapsuleType, RouteWeight, RuntimeType,
};
use capnp::serialize;

/// Cap'n Proto bytes generated by Go test (TestCapnpInteropBytes)
/// This is the serialized form of the interop-test manifest:
/// - schema_version: "1.0"
/// - name: "interop-test"
/// - version: "1.0.0"
/// - type: app
/// - execution.runtime: docker
/// - execution.entrypoint: "nginx:latest"
/// - execution.port: 8080
const GO_GENERATED_CAPNP: &[u8] = &[
    0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 1, 0, 11, 0, 2, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 34, 0,
    0, 0, 41, 0, 0, 0, 106, 0, 0, 0, 45, 0, 0, 0, 50, 0, 0, 0, 44, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 56, 0, 0, 0, 3, 0, 2, 0, 72, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 92, 0, 0,
    0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 46, 48, 0, 0, 0, 0, 0, 105,
    110, 116, 101, 114, 111, 112, 45, 116, 101, 115, 116, 0, 0, 0, 0, 49, 46, 48, 46, 48, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 144, 31, 0, 0, 0, 0, 13, 0, 0, 0, 106, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 103, 105,
    110, 120, 58, 108, 97, 116, 101, 115, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0,
];

/// Test Go → Rust interoperability
/// This test parses Cap'n Proto bytes generated by Go and verifies the fields.
#[test]
fn test_go_to_rust_interop() {
    // Create a copy to avoid const mutation warning
    let bytes = GO_GENERATED_CAPNP.to_vec();

    let reader =
        serialize::read_message(&mut bytes.as_slice(), capnp::message::ReaderOptions::new())
            .expect("Failed to read Go-generated Cap'n Proto message");

    let manifest = reader
        .get_root::<capsule_manifest::Reader>()
        .expect("Failed to get root");

    // Verify basic fields
    assert_eq!(
        manifest.get_schema_version().unwrap().to_string().unwrap(),
        "1.0"
    );
    assert_eq!(
        manifest.get_name().unwrap().to_string().unwrap(),
        "interop-test"
    );
    assert_eq!(
        manifest.get_version().unwrap().to_string().unwrap(),
        "1.0.0"
    );
    assert_eq!(manifest.get_type().unwrap(), CapsuleType::App);

    // Verify execution
    let exec = manifest.get_execution().unwrap();
    assert_eq!(exec.get_runtime().unwrap(), RuntimeType::Docker);
    assert_eq!(
        exec.get_entrypoint().unwrap().to_string().unwrap(),
        "nginx:latest"
    );
    assert_eq!(exec.get_port(), 8080);

    println!(
        "✅ Go → Rust interop test passed: successfully parsed Go-generated Cap'n Proto bytes"
    );
}

#[test]
fn test_capnp_parse_basic() {
    // Create a minimal manifest in Rust to verify the API works
    let mut message = capnp::message::Builder::new_default();
    let mut manifest = message.init_root::<capsule_manifest::Builder>();

    // Set basic fields
    manifest.set_schema_version("1.0");
    manifest.set_name("test-capsule");
    manifest.set_version("0.1.0");
    manifest.set_type(CapsuleType::App);

    // Set execution (using reborrow to avoid move)
    {
        let mut exec = manifest.reborrow().init_execution();
        exec.set_runtime(RuntimeType::Docker);
        exec.set_entrypoint("nginx:latest");
        exec.set_port(80);
        exec.set_startup_timeout(30);
    }

    // Set routing
    {
        let mut routing = manifest.reborrow().init_routing();
        routing.set_weight(RouteWeight::Light);
        routing.set_fallback_to_cloud(true);
    }

    // Serialize
    let bytes = serialize::write_message_to_words(&message);

    // Re-read and verify
    let reader =
        serialize::read_message(&mut bytes.as_slice(), capnp::message::ReaderOptions::new())
            .expect("Failed to read message");

    let parsed = reader
        .get_root::<capsule_manifest::Reader>()
        .expect("Failed to get root");

    assert_eq!(
        parsed.get_schema_version().unwrap().to_string().unwrap(),
        "1.0"
    );
    assert_eq!(
        parsed.get_name().unwrap().to_string().unwrap(),
        "test-capsule"
    );
    assert_eq!(parsed.get_version().unwrap().to_string().unwrap(), "0.1.0");
    assert_eq!(parsed.get_type().unwrap(), CapsuleType::App);

    let exec = parsed.get_execution().unwrap();
    assert_eq!(exec.get_runtime().unwrap(), RuntimeType::Docker);
    assert_eq!(
        exec.get_entrypoint().unwrap().to_string().unwrap(),
        "nginx:latest"
    );
    assert_eq!(exec.get_port(), 80);

    let routing = parsed.get_routing().unwrap();
    assert_eq!(routing.get_weight().unwrap(), RouteWeight::Light);
    assert!(routing.get_fallback_to_cloud());

    println!("✅ Rust Cap'n Proto round-trip test passed");
}

#[test]
fn test_capnp_with_env_vars() {
    let mut message = capnp::message::Builder::new_default();
    let mut manifest = message.init_root::<capsule_manifest::Builder>();

    manifest.set_schema_version("1.0");
    manifest.set_name("env-test");
    manifest.set_version("1.0.0");
    manifest.set_type(CapsuleType::App);

    // Set execution with env vars (using reborrow)
    {
        let mut exec = manifest.reborrow().init_execution();
        exec.set_runtime(RuntimeType::Docker);
        exec.set_entrypoint("alpine");
        exec.set_port(8080);

        // Add environment variables
        let mut env_list = exec.init_env(2);
        {
            let mut env0 = env_list.reborrow().get(0);
            env0.set_key("NODE_ENV");
            env0.set_value("production");
        }
        {
            let mut env1 = env_list.reborrow().get(1);
            env1.set_key("DEBUG");
            env1.set_value("false");
        }
    }

    // Serialize and re-read
    let bytes = serialize::write_message_to_words(&message);

    let reader =
        serialize::read_message(&mut bytes.as_slice(), capnp::message::ReaderOptions::new())
            .expect("Failed to read message");

    let parsed = reader
        .get_root::<capsule_manifest::Reader>()
        .expect("Failed to get root");

    let exec = parsed.get_execution().unwrap();
    let env_list = exec.get_env().unwrap();

    assert_eq!(env_list.len(), 2);

    // Build a map for easier testing
    let mut env_map = std::collections::HashMap::new();
    for i in 0..env_list.len() {
        let env = env_list.get(i);
        let key = env.get_key().unwrap().to_string().unwrap();
        let value = env.get_value().unwrap().to_string().unwrap();
        env_map.insert(key, value);
    }

    assert_eq!(env_map.get("NODE_ENV"), Some(&"production".to_string()));
    assert_eq!(env_map.get("DEBUG"), Some(&"false".to_string()));

    println!("✅ Rust Cap'n Proto env vars test passed");
}

#[test]
fn test_capnp_requirements() {
    let mut message = capnp::message::Builder::new_default();
    let mut manifest = message.init_root::<capsule_manifest::Builder>();

    manifest.set_schema_version("1.0");
    manifest.set_name("gpu-capsule");
    manifest.set_version("1.0.0");
    manifest.set_type(CapsuleType::Inference);

    // Set requirements (using reborrow)
    {
        let mut reqs = manifest.reborrow().init_requirements();
        reqs.set_vram_min_bytes(2 * 1024 * 1024 * 1024); // 2GB
        reqs.set_vram_recommended_bytes(4 * 1024 * 1024 * 1024); // 4GB
        reqs.set_disk_bytes(10 * 1024 * 1024 * 1024); // 10GB

        // Add platforms
        let mut platforms = reqs.init_platform(2);
        platforms.set(0, "darwin-arm64");
        platforms.set(1, "linux-amd64");
    }

    // Serialize and re-read
    let bytes = serialize::write_message_to_words(&message);

    let reader =
        serialize::read_message(&mut bytes.as_slice(), capnp::message::ReaderOptions::new())
            .expect("Failed to read message");

    let parsed = reader
        .get_root::<capsule_manifest::Reader>()
        .expect("Failed to get root");

    let reqs = parsed.get_requirements().unwrap();
    assert_eq!(reqs.get_vram_min_bytes(), 2 * 1024 * 1024 * 1024);
    assert_eq!(reqs.get_vram_recommended_bytes(), 4 * 1024 * 1024 * 1024);
    assert_eq!(reqs.get_disk_bytes(), 10 * 1024 * 1024 * 1024);

    let platforms = reqs.get_platform().unwrap();
    assert_eq!(platforms.len(), 2);
    assert_eq!(
        platforms.get(0).unwrap().to_string().unwrap(),
        "darwin-arm64"
    );
    assert_eq!(
        platforms.get(1).unwrap().to_string().unwrap(),
        "linux-amd64"
    );

    println!("✅ Rust Cap'n Proto requirements test passed");
}
