//! Sandbox Rules Loader for Nacelle
//!
//! This module loads pre-validated sandbox rules from `.nacelle/sandbox_rules.json`.
//! The rules are generated by capsule-cli during the `pack` phase.
//!
//! ## Architecture
//! - **capsule-cli**: Policy resolution and validation (WHAT to allow)
//! - **nacelle**: Rule enforcement (HOW to enforce)

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use crate::verification::sandbox::SandboxPolicy;

/// Pre-computed sandbox rules generated by capsule-cli
///
/// This structure is deserialized from `.nacelle/sandbox_rules.json`
/// which is created during the `capsule pack` phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SandboxRules {
    /// Paths allowed for read-write access
    pub read_write_paths: Vec<PathBuf>,
    
    /// Paths allowed for read-only access
    pub read_only_paths: Vec<PathBuf>,
    
    /// Whether network access is permitted
    pub allow_network: bool,
    
    /// Pre-resolved egress allowlist (optional)
    #[serde(default)]
    pub egress_allow: Vec<EgressRule>,
    
    /// Development mode flag (more permissive)
    #[serde(default)]
    pub development_mode: bool,
}

/// Egress rule entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EgressRule {
    /// Rule type: "domain", "ip", or "cidr"
    #[serde(rename = "type")]
    pub rule_type: String,
    
    /// Rule value (e.g., "api.example.com", "1.1.1.1", "10.0.0.0/8")
    pub value: String,
}

impl SandboxRules {
    /// Convert rules to SandboxPolicy for nacelle enforcement
    pub fn to_policy(self) -> SandboxPolicy {
        SandboxPolicy::new()
            .allow_read_write(self.read_write_paths)
            .allow_read_only(self.read_only_paths)
            .with_network(self.allow_network)
            .with_development_mode(self.development_mode)
    }
}

/// Load pre-computed sandbox rules from `.nacelle/sandbox_rules.json`
///
/// # Arguments
/// * `source_dir` - The root directory of the extracted bundle
///
/// # Returns
/// * `Ok(Some(policy))` - Rules found and successfully loaded
/// * `Ok(None)` - No rules file found (will use default policy)
/// * `Err(e)` - Failed to parse rules file
///
/// # Example
/// ```ignore
/// let policy = load_sandbox_rules(&source_dir)?
///     .unwrap_or_else(|| SandboxPolicy::for_capsule(&source_dir));
/// ```
pub fn load_sandbox_rules(source_dir: &Path) -> Result<Option<SandboxPolicy>> {
    let rules_path = source_dir.join(".nacelle/sandbox_rules.json");
    
    if !rules_path.exists() {
        tracing::warn!(
            "No sandbox_rules.json found at {:?}, using default policy",
            rules_path
        );
        return Ok(None);
    }
    
    tracing::info!("Loading sandbox rules from {:?}", rules_path);
    
    let content = std::fs::read_to_string(&rules_path)
        .with_context(|| format!("Failed to read sandbox_rules.json: {}", rules_path.display()))?;
    
    let rules: SandboxRules = serde_json::from_str(&content)
        .with_context(|| format!("Failed to parse sandbox_rules.json: {}", rules_path.display()))?;
    
    tracing::info!(
        "Loaded sandbox rules: {} read-write paths, {} read-only paths, network: {}",
        rules.read_write_paths.len(),
        rules.read_only_paths.len(),
        rules.allow_network
    );
    
    Ok(Some(rules.to_policy()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_deserialize_sandbox_rules() {
        let json = r#"{
            "read_write_paths": ["/app", "/tmp"],
            "read_only_paths": ["/usr", "/lib"],
            "allow_network": true,
            "development_mode": false
        }"#;

        let rules: SandboxRules = serde_json::from_str(json).unwrap();
        assert_eq!(rules.read_write_paths, vec![PathBuf::from("/app"), PathBuf::from("/tmp")]);
        assert_eq!(rules.read_only_paths, vec![PathBuf::from("/usr"), PathBuf::from("/lib")]);
        assert!(rules.allow_network);
        assert!(!rules.development_mode);
    }

    #[test]
    fn test_deserialize_with_egress_rules() {
        let json = r#"{
            "read_write_paths": ["/app"],
            "read_only_paths": ["/usr"],
            "allow_network": true,
            "egress_allow": [
                {"type": "domain", "value": "api.example.com"},
                {"type": "ip", "value": "1.1.1.1"}
            ]
        }"#;

        let rules: SandboxRules = serde_json::from_str(json).unwrap();
        assert_eq!(rules.egress_allow.len(), 2);
        assert_eq!(rules.egress_allow[0].rule_type, "domain");
        assert_eq!(rules.egress_allow[0].value, "api.example.com");
    }

    #[test]
    fn test_load_sandbox_rules_missing_file() {
        let temp = tempdir().unwrap();
        let result = load_sandbox_rules(temp.path()).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_load_sandbox_rules_valid_file() {
        let temp = tempdir().unwrap();
        let nacelle_dir = temp.path().join(".nacelle");
        fs::create_dir(&nacelle_dir).unwrap();

        let rules_json = r#"{
            "read_write_paths": ["/app"],
            "read_only_paths": ["/usr"],
            "allow_network": true
        }"#;
        fs::write(nacelle_dir.join("sandbox_rules.json"), rules_json).unwrap();

        let policy = load_sandbox_rules(temp.path()).unwrap().unwrap();
        assert_eq!(policy.read_write_paths, vec![PathBuf::from("/app")]);
    }

    #[test]
    fn test_rules_to_policy_conversion() {
        let rules = SandboxRules {
            read_write_paths: vec![PathBuf::from("/app")],
            read_only_paths: vec![PathBuf::from("/usr")],
            allow_network: true,
            egress_allow: vec![],
            development_mode: false,
        };

        let policy = rules.to_policy();
        assert_eq!(policy.read_write_paths, vec![PathBuf::from("/app")]);
        assert_eq!(policy.read_only_paths, vec![PathBuf::from("/usr")]);
        assert!(policy.allow_network);
        assert!(!policy.development_mode);
    }
}
