// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunPlan v0: normalized execution plan (Phase 2)
// Shared between coordinator.proto and engine.proto
type RunPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traceability
	CapsuleId string `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Runtime selection
	//
	// Types that are valid to be assigned to Runtime:
	//
	//	*RunPlan_Docker
	//	*RunPlan_Native
	//	*RunPlan_PythonUv
	Runtime isRunPlan_Runtime `protobuf_oneof:"runtime"`
	// Resources
	CpuCores    uint32 `protobuf:"varint,20,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`          // optional
	MemoryBytes uint64 `protobuf:"varint,21,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // optional
	GpuProfile  string `protobuf:"bytes,22,opt,name=gpu_profile,json=gpuProfile,proto3" json:"gpu_profile,omitempty"`     // optional, e.g., "none" | "cuda:L4:1"
	// Network
	EgressAllowlist []string `protobuf:"bytes,30,rep,name=egress_allowlist,json=egressAllowlist,proto3" json:"egress_allowlist,omitempty"` // optional CIDR/host list
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunPlan) Reset() {
	*x = RunPlan{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPlan) ProtoMessage() {}

func (x *RunPlan) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPlan.ProtoReflect.Descriptor instead.
func (*RunPlan) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *RunPlan) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *RunPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunPlan) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RunPlan) GetRuntime() isRunPlan_Runtime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *RunPlan) GetDocker() *DockerRuntime {
	if x != nil {
		if x, ok := x.Runtime.(*RunPlan_Docker); ok {
			return x.Docker
		}
	}
	return nil
}

func (x *RunPlan) GetNative() *NativeRuntime {
	if x != nil {
		if x, ok := x.Runtime.(*RunPlan_Native); ok {
			return x.Native
		}
	}
	return nil
}

func (x *RunPlan) GetPythonUv() *PythonUvRuntime {
	if x != nil {
		if x, ok := x.Runtime.(*RunPlan_PythonUv); ok {
			return x.PythonUv
		}
	}
	return nil
}

func (x *RunPlan) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RunPlan) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RunPlan) GetGpuProfile() string {
	if x != nil {
		return x.GpuProfile
	}
	return ""
}

func (x *RunPlan) GetEgressAllowlist() []string {
	if x != nil {
		return x.EgressAllowlist
	}
	return nil
}

type isRunPlan_Runtime interface {
	isRunPlan_Runtime()
}

type RunPlan_Docker struct {
	Docker *DockerRuntime `protobuf:"bytes,10,opt,name=docker,proto3,oneof"`
}

type RunPlan_Native struct {
	Native *NativeRuntime `protobuf:"bytes,11,opt,name=native,proto3,oneof"`
}

type RunPlan_PythonUv struct {
	PythonUv *PythonUvRuntime `protobuf:"bytes,12,opt,name=python_uv,json=pythonUv,proto3,oneof"` // Optional: enable only if supported
}

func (*RunPlan_Docker) isRunPlan_Runtime() {}

func (*RunPlan_Native) isRunPlan_Runtime() {}

func (*RunPlan_PythonUv) isRunPlan_Runtime() {}

type DockerRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`   // optional
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"` // entrypoint/command
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"` // optional
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`                               // optional
	Ports         []*Port                `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	Mounts        []*Mount               `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerRuntime) Reset() {
	*x = DockerRuntime{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerRuntime) ProtoMessage() {}

func (x *DockerRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerRuntime.ProtoReflect.Descriptor instead.
func (*DockerRuntime) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *DockerRuntime) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DockerRuntime) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *DockerRuntime) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DockerRuntime) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DockerRuntime) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *DockerRuntime) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DockerRuntime) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DockerRuntime) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type NativeRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BinaryPath    string                 `protobuf:"bytes,1,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeRuntime) Reset() {
	*x = NativeRuntime{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeRuntime) ProtoMessage() {}

func (x *NativeRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeRuntime.ProtoReflect.Descriptor instead.
func (*NativeRuntime) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *NativeRuntime) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *NativeRuntime) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *NativeRuntime) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *NativeRuntime) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type PythonUvRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entrypoint    string                 `protobuf:"bytes,1,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Ports         []*Port                `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonUvRuntime) Reset() {
	*x = PythonUvRuntime{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonUvRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonUvRuntime) ProtoMessage() {}

func (x *PythonUvRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonUvRuntime.ProtoReflect.Descriptor instead.
func (*PythonUvRuntime) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *PythonUvRuntime) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *PythonUvRuntime) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PythonUvRuntime) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *PythonUvRuntime) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *PythonUvRuntime) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort uint32                 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HostPort      uint32                 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"` // optional
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                  // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Port) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *Port) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x15onescluster.common.v1\"\xb4\x03\n" +
	"\aRunPlan\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12>\n" +
	"\x06docker\x18\n" +
	" \x01(\v2$.onescluster.common.v1.DockerRuntimeH\x00R\x06docker\x12>\n" +
	"\x06native\x18\v \x01(\v2$.onescluster.common.v1.NativeRuntimeH\x00R\x06native\x12E\n" +
	"\tpython_uv\x18\f \x01(\v2&.onescluster.common.v1.PythonUvRuntimeH\x00R\bpythonUv\x12\x1b\n" +
	"\tcpu_cores\x18\x14 \x01(\rR\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x15 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vgpu_profile\x18\x16 \x01(\tR\n" +
	"gpuProfile\x12)\n" +
	"\x10egress_allowlist\x18\x1e \x03(\tR\x0fegressAllowlistB\t\n" +
	"\aruntime\"\xee\x02\n" +
	"\rDockerRuntime\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12?\n" +
	"\x03env\x18\x04 \x03(\v2-.onescluster.common.v1.DockerRuntime.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x121\n" +
	"\x05ports\x18\a \x03(\v2\x1b.onescluster.common.v1.PortR\x05ports\x124\n" +
	"\x06mounts\x18\b \x03(\v2\x1c.onescluster.common.v1.MountR\x06mounts\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\rNativeRuntime\x12\x1f\n" +
	"\vbinary_path\x18\x01 \x01(\tR\n" +
	"binaryPath\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12?\n" +
	"\x03env\x18\x03 \x03(\v2-.onescluster.common.v1.NativeRuntime.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x02\n" +
	"\x0fPythonUvRuntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x01 \x01(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12A\n" +
	"\x03env\x18\x03 \x03(\v2/.onescluster.common.v1.PythonUvRuntime.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x121\n" +
	"\x05ports\x18\x05 \x03(\v2\x1b.onescluster.common.v1.PortR\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x04Port\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"S\n" +
	"\x05Mount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonlyB4Z2github.com/onescluster/coordinator/pkg/proto;protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_proto_goTypes = []any{
	(*RunPlan)(nil),         // 0: onescluster.common.v1.RunPlan
	(*DockerRuntime)(nil),   // 1: onescluster.common.v1.DockerRuntime
	(*NativeRuntime)(nil),   // 2: onescluster.common.v1.NativeRuntime
	(*PythonUvRuntime)(nil), // 3: onescluster.common.v1.PythonUvRuntime
	(*Port)(nil),            // 4: onescluster.common.v1.Port
	(*Mount)(nil),           // 5: onescluster.common.v1.Mount
	nil,                     // 6: onescluster.common.v1.DockerRuntime.EnvEntry
	nil,                     // 7: onescluster.common.v1.NativeRuntime.EnvEntry
	nil,                     // 8: onescluster.common.v1.PythonUvRuntime.EnvEntry
}
var file_common_proto_depIdxs = []int32{
	1, // 0: onescluster.common.v1.RunPlan.docker:type_name -> onescluster.common.v1.DockerRuntime
	2, // 1: onescluster.common.v1.RunPlan.native:type_name -> onescluster.common.v1.NativeRuntime
	3, // 2: onescluster.common.v1.RunPlan.python_uv:type_name -> onescluster.common.v1.PythonUvRuntime
	6, // 3: onescluster.common.v1.DockerRuntime.env:type_name -> onescluster.common.v1.DockerRuntime.EnvEntry
	4, // 4: onescluster.common.v1.DockerRuntime.ports:type_name -> onescluster.common.v1.Port
	5, // 5: onescluster.common.v1.DockerRuntime.mounts:type_name -> onescluster.common.v1.Mount
	7, // 6: onescluster.common.v1.NativeRuntime.env:type_name -> onescluster.common.v1.NativeRuntime.EnvEntry
	8, // 7: onescluster.common.v1.PythonUvRuntime.env:type_name -> onescluster.common.v1.PythonUvRuntime.EnvEntry
	4, // 8: onescluster.common.v1.PythonUvRuntime.ports:type_name -> onescluster.common.v1.Port
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[0].OneofWrappers = []any{
		(*RunPlan_Docker)(nil),
		(*RunPlan_Native)(nil),
		(*RunPlan_PythonUv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
