// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadPhase int32

const (
	WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED WorkloadPhase = 0
	WorkloadPhase_WORKLOAD_PHASE_PENDING     WorkloadPhase = 1
	WorkloadPhase_WORKLOAD_PHASE_RUNNING     WorkloadPhase = 2
	WorkloadPhase_WORKLOAD_PHASE_FAILED      WorkloadPhase = 3
	WorkloadPhase_WORKLOAD_PHASE_SUCCEEDED   WorkloadPhase = 4
)

// Enum value maps for WorkloadPhase.
var (
	WorkloadPhase_name = map[int32]string{
		0: "WORKLOAD_PHASE_UNSPECIFIED",
		1: "WORKLOAD_PHASE_PENDING",
		2: "WORKLOAD_PHASE_RUNNING",
		3: "WORKLOAD_PHASE_FAILED",
		4: "WORKLOAD_PHASE_SUCCEEDED",
	}
	WorkloadPhase_value = map[string]int32{
		"WORKLOAD_PHASE_UNSPECIFIED": 0,
		"WORKLOAD_PHASE_PENDING":     1,
		"WORKLOAD_PHASE_RUNNING":     2,
		"WORKLOAD_PHASE_FAILED":      3,
		"WORKLOAD_PHASE_SUCCEEDED":   4,
	}
)

func (x WorkloadPhase) Enum() *WorkloadPhase {
	p := new(WorkloadPhase)
	*p = x
	return p
}

func (x WorkloadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_proto_enumTypes[0].Descriptor()
}

func (WorkloadPhase) Type() protoreflect.EnumType {
	return &file_proto_coordinator_proto_enumTypes[0]
}

func (x WorkloadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadPhase.Descriptor instead.
func (WorkloadPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

type TaintEffect int32

const (
	TaintEffect_TAINT_EFFECT_UNSPECIFIED        TaintEffect = 0
	TaintEffect_TAINT_EFFECT_NO_SCHEDULE        TaintEffect = 1
	TaintEffect_TAINT_EFFECT_PREFER_NO_SCHEDULE TaintEffect = 2
)

// Enum value maps for TaintEffect.
var (
	TaintEffect_name = map[int32]string{
		0: "TAINT_EFFECT_UNSPECIFIED",
		1: "TAINT_EFFECT_NO_SCHEDULE",
		2: "TAINT_EFFECT_PREFER_NO_SCHEDULE",
	}
	TaintEffect_value = map[string]int32{
		"TAINT_EFFECT_UNSPECIFIED":        0,
		"TAINT_EFFECT_NO_SCHEDULE":        1,
		"TAINT_EFFECT_PREFER_NO_SCHEDULE": 2,
	}
)

func (x TaintEffect) Enum() *TaintEffect {
	p := new(TaintEffect)
	*p = x
	return p
}

func (x TaintEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaintEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_proto_enumTypes[1].Descriptor()
}

func (TaintEffect) Type() protoreflect.EnumType {
	return &file_proto_coordinator_proto_enumTypes[1]
}

func (x TaintEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaintEffect.Descriptor instead.
func (TaintEffect) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

// Report submitted by Agent containing current hardware + workload state
type StatusReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *RigStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReportRequest) Reset() {
	*x = StatusReportRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReportRequest) ProtoMessage() {}

func (x *StatusReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReportRequest.ProtoReflect.Descriptor instead.
func (*StatusReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *StatusReportRequest) GetStatus() *RigStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatusReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReportResponse) Reset() {
	*x = StatusReportResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReportResponse) ProtoMessage() {}

func (x *StatusReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReportResponse.ProtoReflect.Descriptor instead.
func (*StatusReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Agent state snapshot (source of truth for reconciliation)
type RigStatus struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RigId                 string                 `protobuf:"bytes,1,opt,name=rig_id,json=rigId,proto3" json:"rig_id,omitempty"`                                                      // Unique Rig identifier (hostname)
	Hardware              *HardwareState         `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`                                                             // Hardware metrics (VRAM, drivers, GPUs)
	RunningWorkloads      []*WorkloadStatus      `protobuf:"bytes,3,rep,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`                     // Workloads currently running on Agent
	Taints                []*Taint               `protobuf:"bytes,4,rep,name=taints,proto3" json:"taints,omitempty"`                                                                 // Scheduling taints advertised by Agent
	ReportedAtUnixSeconds uint64                 `protobuf:"varint,5,opt,name=reported_at_unix_seconds,json=reportedAtUnixSeconds,proto3" json:"reported_at_unix_seconds,omitempty"` // Timestamp of this report (epoch seconds)
	IsMock                bool                   `protobuf:"varint,6,opt,name=is_mock,json=isMock,proto3" json:"is_mock,omitempty"`                                                  // Whether this is mock data (for testing)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RigStatus) Reset() {
	*x = RigStatus{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RigStatus) ProtoMessage() {}

func (x *RigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RigStatus.ProtoReflect.Descriptor instead.
func (*RigStatus) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *RigStatus) GetRigId() string {
	if x != nil {
		return x.RigId
	}
	return ""
}

func (x *RigStatus) GetHardware() *HardwareState {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RigStatus) GetRunningWorkloads() []*WorkloadStatus {
	if x != nil {
		return x.RunningWorkloads
	}
	return nil
}

func (x *RigStatus) GetTaints() []*Taint {
	if x != nil {
		return x.Taints
	}
	return nil
}

func (x *RigStatus) GetReportedAtUnixSeconds() uint64 {
	if x != nil {
		return x.ReportedAtUnixSeconds
	}
	return 0
}

func (x *RigStatus) GetIsMock() bool {
	if x != nil {
		return x.IsMock
	}
	return false
}

// Hardware snapshot for a Rig
type HardwareState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Gpus                []*GpuInfo             `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`                                                            // List of GPUs on this Rig
	SystemCudaVersion   string                 `protobuf:"bytes,2,opt,name=system_cuda_version,json=systemCudaVersion,proto3" json:"system_cuda_version,omitempty"`       // System CUDA version (e.g., "12.2")
	SystemDriverVersion string                 `protobuf:"bytes,3,opt,name=system_driver_version,json=systemDriverVersion,proto3" json:"system_driver_version,omitempty"` // NVIDIA driver version (e.g., "525.60.11")
	TotalVramBytes      uint64                 `protobuf:"varint,4,opt,name=total_vram_bytes,json=totalVramBytes,proto3" json:"total_vram_bytes,omitempty"`               // Sum of VRAM across all GPUs
	UsedVramBytes       uint64                 `protobuf:"varint,5,opt,name=used_vram_bytes,json=usedVramBytes,proto3" json:"used_vram_bytes,omitempty"`                  // VRAM currently consumed by running workloads
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HardwareState) Reset() {
	*x = HardwareState{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareState) ProtoMessage() {}

func (x *HardwareState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareState.ProtoReflect.Descriptor instead.
func (*HardwareState) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HardwareState) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareState) GetSystemCudaVersion() string {
	if x != nil {
		return x.SystemCudaVersion
	}
	return ""
}

func (x *HardwareState) GetSystemDriverVersion() string {
	if x != nil {
		return x.SystemDriverVersion
	}
	return ""
}

func (x *HardwareState) GetTotalVramBytes() uint64 {
	if x != nil {
		return x.TotalVramBytes
	}
	return 0
}

func (x *HardwareState) GetUsedVramBytes() uint64 {
	if x != nil {
		return x.UsedVramBytes
	}
	return 0
}

// GPU information (maps to Rust GpuInfo)
type GpuInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Index                 uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                                               // GPU index (0-based)
	DeviceName            string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`                                    // GPU name (e.g., "NVIDIA GeForce RTX 4090")
	VramTotalBytes        uint64                 `protobuf:"varint,3,opt,name=vram_total_bytes,json=vramTotalBytes,proto3" json:"vram_total_bytes,omitempty"`                     // Total VRAM in bytes
	CudaComputeCapability string                 `protobuf:"bytes,4,opt,name=cuda_compute_capability,json=cudaComputeCapability,proto3" json:"cuda_compute_capability,omitempty"` // CUDA compute capability (e.g., "8.9")
	VramAvailableBytes    uint64                 `protobuf:"varint,5,opt,name=vram_available_bytes,json=vramAvailableBytes,proto3" json:"vram_available_bytes,omitempty"`         // Currently available VRAM (optional)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *GpuInfo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GpuInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GpuInfo) GetVramTotalBytes() uint64 {
	if x != nil {
		return x.VramTotalBytes
	}
	return 0
}

func (x *GpuInfo) GetCudaComputeCapability() string {
	if x != nil {
		return x.CudaComputeCapability
	}
	return ""
}

func (x *GpuInfo) GetVramAvailableBytes() uint64 {
	if x != nil {
		return x.VramAvailableBytes
	}
	return 0
}

// Workload instance currently running on the Rig
type WorkloadStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId        string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`                         // Unique workload identifier
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                       // Human-friendly workload name (optional)
	ReservedVramBytes uint64                 `protobuf:"varint,3,opt,name=reserved_vram_bytes,json=reservedVramBytes,proto3" json:"reserved_vram_bytes,omitempty"` // VRAM reserved by this workload
	Phase             WorkloadPhase          `protobuf:"varint,4,opt,name=phase,proto3,enum=onescluster.coordinator.v1.WorkloadPhase" json:"phase,omitempty"`      // Observed execution phase
	Pid               uint64                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                                                        // Process ID of the container (0 = unknown)
	ObservedVramBytes uint64                 `protobuf:"varint,6,opt,name=observed_vram_bytes,json=observedVramBytes,proto3" json:"observed_vram_bytes,omitempty"` // VRAM measured in bytes (fallback to reserved)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadStatus) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadStatus) GetReservedVramBytes() uint64 {
	if x != nil {
		return x.ReservedVramBytes
	}
	return 0
}

func (x *WorkloadStatus) GetPhase() WorkloadPhase {
	if x != nil {
		return x.Phase
	}
	return WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED
}

func (x *WorkloadStatus) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *WorkloadStatus) GetObservedVramBytes() uint64 {
	if x != nil {
		return x.ObservedVramBytes
	}
	return 0
}

// Node-level taints advertised for scheduling decisions
type Taint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Effect        TaintEffect            `protobuf:"varint,3,opt,name=effect,proto3,enum=onescluster.coordinator.v1.TaintEffect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taint) Reset() {
	*x = Taint{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taint) ProtoMessage() {}

func (x *Taint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taint.ProtoReflect.Descriptor instead.
func (*Taint) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *Taint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Taint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Taint) GetEffect() TaintEffect {
	if x != nil {
		return x.Effect
	}
	return TaintEffect_TAINT_EFFECT_UNSPECIFIED
}

// Request to deploy a workload (Coordinator → Agent)
type DeployWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`       // Unique workload identifier
	Manifest      *AdePManifest          `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`                             // Strongly typed adep manifest
	ManifestJson  string                 `protobuf:"bytes,3,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // Original JSON payload (for compatibility)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployWorkloadRequest) Reset() {
	*x = DeployWorkloadRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkloadRequest) ProtoMessage() {}

func (x *DeployWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeployWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *DeployWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *DeployWorkloadRequest) GetManifest() *AdePManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *DeployWorkloadRequest) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

// Response to deploy request
type DeployWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Success message or error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployWorkloadResponse) Reset() {
	*x = DeployWorkloadResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployWorkloadResponse) ProtoMessage() {}

func (x *DeployWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeployWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *DeployWorkloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployWorkloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Strict schema for adep.json manifest
type AdePManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Workload name
	Scheduling    *SchedulingConfig      `protobuf:"bytes,2,opt,name=scheduling,proto3" json:"scheduling,omitempty"`                                                                       // Scheduling preferences/constraints
	Compute       *ComputeConfig         `protobuf:"bytes,3,opt,name=compute,proto3" json:"compute,omitempty"`                                                                             // Container execution parameters
	Volumes       []*Volume              `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`                                                                             // Volume mounts
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Arbitrary metadata for future use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdePManifest) Reset() {
	*x = AdePManifest{}
	mi := &file_proto_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdePManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdePManifest) ProtoMessage() {}

func (x *AdePManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdePManifest.ProtoReflect.Descriptor instead.
func (*AdePManifest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *AdePManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdePManifest) GetScheduling() *SchedulingConfig {
	if x != nil {
		return x.Scheduling
	}
	return nil
}

func (x *AdePManifest) GetCompute() *ComputeConfig {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *AdePManifest) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *AdePManifest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SchedulingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpu           *GpuConstraints        `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`           // GPU requirements
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // Scheduling strategy hint (e.g., "best_fit")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulingConfig) Reset() {
	*x = SchedulingConfig{}
	mi := &file_proto_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingConfig) ProtoMessage() {}

func (x *SchedulingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingConfig.ProtoReflect.Descriptor instead.
func (*SchedulingConfig) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *SchedulingConfig) GetGpu() *GpuConstraints {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *SchedulingConfig) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type GpuConstraints struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VramMinGb      uint64                 `protobuf:"varint,1,opt,name=vram_min_gb,json=vramMinGb,proto3" json:"vram_min_gb,omitempty"`               // Minimum VRAM requirement (GB)
	CudaVersionMin string                 `protobuf:"bytes,2,opt,name=cuda_version_min,json=cudaVersionMin,proto3" json:"cuda_version_min,omitempty"` // Minimum CUDA version requirement
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GpuConstraints) Reset() {
	*x = GpuConstraints{}
	mi := &file_proto_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuConstraints) ProtoMessage() {}

func (x *GpuConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuConstraints.ProtoReflect.Descriptor instead.
func (*GpuConstraints) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *GpuConstraints) GetVramMinGb() uint64 {
	if x != nil {
		return x.VramMinGb
	}
	return 0
}

func (x *GpuConstraints) GetCudaVersionMin() string {
	if x != nil {
		return x.CudaVersionMin
	}
	return ""
}

type ComputeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`                                                                       // OCI image reference
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Container args (entrypoint + args)
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables key/value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeConfig) Reset() {
	*x = ComputeConfig{}
	mi := &file_proto_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeConfig) ProtoMessage() {}

func (x *ComputeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeConfig.ProtoReflect.Descriptor instead.
func (*ComputeConfig) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *ComputeConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ComputeConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ComputeConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`               // Mount type (e.g., "bind")
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`           // Host path
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"` // Container path
	Readonly      bool                   `protobuf:"varint,4,opt,name=readonly,proto3" json:"readonly,omitempty"`      // Read-only flag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_proto_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *Volume) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Volume) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Volume) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Volume) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\x1aonescluster.coordinator.v1\"T\n" +
	"\x13StatusReportRequest\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.onescluster.coordinator.v1.RigStatusR\x06status\"J\n" +
	"\x14StatusReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x02\n" +
	"\tRigStatus\x12\x15\n" +
	"\x06rig_id\x18\x01 \x01(\tR\x05rigId\x12E\n" +
	"\bhardware\x18\x02 \x01(\v2).onescluster.coordinator.v1.HardwareStateR\bhardware\x12W\n" +
	"\x11running_workloads\x18\x03 \x03(\v2*.onescluster.coordinator.v1.WorkloadStatusR\x10runningWorkloads\x129\n" +
	"\x06taints\x18\x04 \x03(\v2!.onescluster.coordinator.v1.TaintR\x06taints\x127\n" +
	"\x18reported_at_unix_seconds\x18\x05 \x01(\x04R\x15reportedAtUnixSeconds\x12\x17\n" +
	"\ais_mock\x18\x06 \x01(\bR\x06isMock\"\xfe\x01\n" +
	"\rHardwareState\x127\n" +
	"\x04gpus\x18\x01 \x03(\v2#.onescluster.coordinator.v1.GpuInfoR\x04gpus\x12.\n" +
	"\x13system_cuda_version\x18\x02 \x01(\tR\x11systemCudaVersion\x122\n" +
	"\x15system_driver_version\x18\x03 \x01(\tR\x13systemDriverVersion\x12(\n" +
	"\x10total_vram_bytes\x18\x04 \x01(\x04R\x0etotalVramBytes\x12&\n" +
	"\x0fused_vram_bytes\x18\x05 \x01(\x04R\rusedVramBytes\"\xd4\x01\n" +
	"\aGpuInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12(\n" +
	"\x10vram_total_bytes\x18\x03 \x01(\x04R\x0evramTotalBytes\x126\n" +
	"\x17cuda_compute_capability\x18\x04 \x01(\tR\x15cudaComputeCapability\x120\n" +
	"\x14vram_available_bytes\x18\x05 \x01(\x04R\x12vramAvailableBytes\"\xf8\x01\n" +
	"\x0eWorkloadStatus\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13reserved_vram_bytes\x18\x03 \x01(\x04R\x11reservedVramBytes\x12?\n" +
	"\x05phase\x18\x04 \x01(\x0e2).onescluster.coordinator.v1.WorkloadPhaseR\x05phase\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x04R\x03pid\x12.\n" +
	"\x13observed_vram_bytes\x18\x06 \x01(\x04R\x11observedVramBytes\"p\n" +
	"\x05Taint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12?\n" +
	"\x06effect\x18\x03 \x01(\x0e2'.onescluster.coordinator.v1.TaintEffectR\x06effect\"\xa3\x01\n" +
	"\x15DeployWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12D\n" +
	"\bmanifest\x18\x02 \x01(\v2(.onescluster.coordinator.v1.AdePManifestR\bmanifest\x12#\n" +
	"\rmanifest_json\x18\x03 \x01(\tR\fmanifestJson\"L\n" +
	"\x16DeployWorkloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x03\n" +
	"\fAdePManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\n" +
	"scheduling\x18\x02 \x01(\v2,.onescluster.coordinator.v1.SchedulingConfigR\n" +
	"scheduling\x12C\n" +
	"\acompute\x18\x03 \x01(\v2).onescluster.coordinator.v1.ComputeConfigR\acompute\x12<\n" +
	"\avolumes\x18\x04 \x03(\v2\".onescluster.coordinator.v1.VolumeR\avolumes\x12R\n" +
	"\bmetadata\x18\x05 \x03(\v26.onescluster.coordinator.v1.AdePManifest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x10SchedulingConfig\x12<\n" +
	"\x03gpu\x18\x01 \x01(\v2*.onescluster.coordinator.v1.GpuConstraintsR\x03gpu\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\"Z\n" +
	"\x0eGpuConstraints\x12\x1e\n" +
	"\vvram_min_gb\x18\x01 \x01(\x04R\tvramMinGb\x12(\n" +
	"\x10cuda_version_min\x18\x02 \x01(\tR\x0ecudaVersionMin\"\xb7\x01\n" +
	"\rComputeConfig\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12D\n" +
	"\x03env\x18\x03 \x03(\v22.onescluster.coordinator.v1.ComputeConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x06Volume\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1a\n" +
	"\breadonly\x18\x04 \x01(\bR\breadonly*\xa0\x01\n" +
	"\rWorkloadPhase\x12\x1e\n" +
	"\x1aWORKLOAD_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_PENDING\x10\x01\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_RUNNING\x10\x02\x12\x19\n" +
	"\x15WORKLOAD_PHASE_FAILED\x10\x03\x12\x1c\n" +
	"\x18WORKLOAD_PHASE_SUCCEEDED\x10\x04*n\n" +
	"\vTaintEffect\x12\x1c\n" +
	"\x18TAINT_EFFECT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TAINT_EFFECT_NO_SCHEDULE\x10\x01\x12#\n" +
	"\x1fTAINT_EFFECT_PREFER_NO_SCHEDULE\x10\x022\xf9\x01\n" +
	"\vCoordinator\x12q\n" +
	"\fReportStatus\x12/.onescluster.coordinator.v1.StatusReportRequest\x1a0.onescluster.coordinator.v1.StatusReportResponse\x12w\n" +
	"\x0eDeployWorkload\x121.onescluster.coordinator.v1.DeployWorkloadRequest\x1a2.onescluster.coordinator.v1.DeployWorkloadResponseB4Z2github.com/onescluster/coordinator/pkg/proto;protob\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_coordinator_proto_goTypes = []any{
	(WorkloadPhase)(0),             // 0: onescluster.coordinator.v1.WorkloadPhase
	(TaintEffect)(0),               // 1: onescluster.coordinator.v1.TaintEffect
	(*StatusReportRequest)(nil),    // 2: onescluster.coordinator.v1.StatusReportRequest
	(*StatusReportResponse)(nil),   // 3: onescluster.coordinator.v1.StatusReportResponse
	(*RigStatus)(nil),              // 4: onescluster.coordinator.v1.RigStatus
	(*HardwareState)(nil),          // 5: onescluster.coordinator.v1.HardwareState
	(*GpuInfo)(nil),                // 6: onescluster.coordinator.v1.GpuInfo
	(*WorkloadStatus)(nil),         // 7: onescluster.coordinator.v1.WorkloadStatus
	(*Taint)(nil),                  // 8: onescluster.coordinator.v1.Taint
	(*DeployWorkloadRequest)(nil),  // 9: onescluster.coordinator.v1.DeployWorkloadRequest
	(*DeployWorkloadResponse)(nil), // 10: onescluster.coordinator.v1.DeployWorkloadResponse
	(*AdePManifest)(nil),           // 11: onescluster.coordinator.v1.AdePManifest
	(*SchedulingConfig)(nil),       // 12: onescluster.coordinator.v1.SchedulingConfig
	(*GpuConstraints)(nil),         // 13: onescluster.coordinator.v1.GpuConstraints
	(*ComputeConfig)(nil),          // 14: onescluster.coordinator.v1.ComputeConfig
	(*Volume)(nil),                 // 15: onescluster.coordinator.v1.Volume
	nil,                            // 16: onescluster.coordinator.v1.AdePManifest.MetadataEntry
	nil,                            // 17: onescluster.coordinator.v1.ComputeConfig.EnvEntry
}
var file_proto_coordinator_proto_depIdxs = []int32{
	4,  // 0: onescluster.coordinator.v1.StatusReportRequest.status:type_name -> onescluster.coordinator.v1.RigStatus
	5,  // 1: onescluster.coordinator.v1.RigStatus.hardware:type_name -> onescluster.coordinator.v1.HardwareState
	7,  // 2: onescluster.coordinator.v1.RigStatus.running_workloads:type_name -> onescluster.coordinator.v1.WorkloadStatus
	8,  // 3: onescluster.coordinator.v1.RigStatus.taints:type_name -> onescluster.coordinator.v1.Taint
	6,  // 4: onescluster.coordinator.v1.HardwareState.gpus:type_name -> onescluster.coordinator.v1.GpuInfo
	0,  // 5: onescluster.coordinator.v1.WorkloadStatus.phase:type_name -> onescluster.coordinator.v1.WorkloadPhase
	1,  // 6: onescluster.coordinator.v1.Taint.effect:type_name -> onescluster.coordinator.v1.TaintEffect
	11, // 7: onescluster.coordinator.v1.DeployWorkloadRequest.manifest:type_name -> onescluster.coordinator.v1.AdePManifest
	12, // 8: onescluster.coordinator.v1.AdePManifest.scheduling:type_name -> onescluster.coordinator.v1.SchedulingConfig
	14, // 9: onescluster.coordinator.v1.AdePManifest.compute:type_name -> onescluster.coordinator.v1.ComputeConfig
	15, // 10: onescluster.coordinator.v1.AdePManifest.volumes:type_name -> onescluster.coordinator.v1.Volume
	16, // 11: onescluster.coordinator.v1.AdePManifest.metadata:type_name -> onescluster.coordinator.v1.AdePManifest.MetadataEntry
	13, // 12: onescluster.coordinator.v1.SchedulingConfig.gpu:type_name -> onescluster.coordinator.v1.GpuConstraints
	17, // 13: onescluster.coordinator.v1.ComputeConfig.env:type_name -> onescluster.coordinator.v1.ComputeConfig.EnvEntry
	2,  // 14: onescluster.coordinator.v1.Coordinator.ReportStatus:input_type -> onescluster.coordinator.v1.StatusReportRequest
	9,  // 15: onescluster.coordinator.v1.Coordinator.DeployWorkload:input_type -> onescluster.coordinator.v1.DeployWorkloadRequest
	3,  // 16: onescluster.coordinator.v1.Coordinator.ReportStatus:output_type -> onescluster.coordinator.v1.StatusReportResponse
	10, // 17: onescluster.coordinator.v1.Coordinator.DeployWorkload:output_type -> onescluster.coordinator.v1.DeployWorkloadResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		EnumInfos:         file_proto_coordinator_proto_enumTypes,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
