// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`                        // If true, stream updates. If false, return current content and close.
	TailLines     uint64                 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // Number of lines to return from the end (0 for all/default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTailLines() uint64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type EngineLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO8601
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`       // "stdout" or "stderr"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineLogEntry) Reset() {
	*x = EngineLogEntry{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineLogEntry) ProtoMessage() {}

func (x *EngineLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineLogEntry.ProtoReflect.Descriptor instead.
func (*EngineLogEntry) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *EngineLogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *EngineLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EngineLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcesRequest) Reset() {
	*x = GetResourcesRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesRequest) ProtoMessage() {}

func (x *GetResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetResourcesRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

type GetSystemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatusRequest) Reset() {
	*x = GetSystemStatusRequest{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatusRequest) ProtoMessage() {}

func (x *GetSystemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatusRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

type DeployRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	// Types that are valid to be assigned to Manifest:
	//
	//	*DeployRequest_AdepJson
	//	*DeployRequest_TomlContent
	//	*DeployRequest_RunPlan
	Manifest      isDeployRequest_Manifest `protobuf_oneof:"manifest"`
	OciImage      string                   `protobuf:"bytes,3,opt,name=oci_image,json=ociImage,proto3" json:"oci_image,omitempty"` // Optional, can be derived from manifest
	Digest        string                   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`                     // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *DeployRequest) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *DeployRequest) GetManifest() isDeployRequest_Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Deprecated: Marked as deprecated in engine.proto.
func (x *DeployRequest) GetAdepJson() []byte {
	if x != nil {
		if x, ok := x.Manifest.(*DeployRequest_AdepJson); ok {
			return x.AdepJson
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in engine.proto.
func (x *DeployRequest) GetTomlContent() string {
	if x != nil {
		if x, ok := x.Manifest.(*DeployRequest_TomlContent); ok {
			return x.TomlContent
		}
	}
	return ""
}

func (x *DeployRequest) GetRunPlan() *RunPlan {
	if x != nil {
		if x, ok := x.Manifest.(*DeployRequest_RunPlan); ok {
			return x.RunPlan
		}
	}
	return nil
}

func (x *DeployRequest) GetOciImage() string {
	if x != nil {
		return x.OciImage
	}
	return ""
}

func (x *DeployRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type isDeployRequest_Manifest interface {
	isDeployRequest_Manifest()
}

type DeployRequest_AdepJson struct {
	// Deprecated: Marked as deprecated in engine.proto.
	AdepJson []byte `protobuf:"bytes,2,opt,name=adep_json,json=adepJson,proto3,oneof"` // Legacy JSON support
}

type DeployRequest_TomlContent struct {
	// Deprecated: Marked as deprecated in engine.proto.
	TomlContent string `protobuf:"bytes,5,opt,name=toml_content,json=tomlContent,proto3,oneof"` // TOML manifest content
}

type DeployRequest_RunPlan struct {
	RunPlan *RunPlan `protobuf:"bytes,6,opt,name=run_plan,json=runPlan,proto3,oneof"` // Normalized execution plan (preferred)
}

func (*DeployRequest_AdepJson) isDeployRequest_Manifest() {}

func (*DeployRequest_TomlContent) isDeployRequest_Manifest() {}

func (*DeployRequest_RunPlan) isDeployRequest_Manifest() {}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LocalUrl      string                 `protobuf:"bytes,3,opt,name=local_url,json=localUrl,proto3" json:"local_url,omitempty"` // e.g., "http://verification-capsule.local"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResponse) GetLocalUrl() string {
	if x != nil {
		return x.LocalUrl
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *StopResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      uint64                 `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes     uint64                 `protobuf:"varint,3,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	BackendMode   string                 `protobuf:"bytes,4,opt,name=backend_mode,json=backendMode,proto3" json:"backend_mode,omitempty"` // "cpu", "gpu", or "mock"
	VpnIp         string                 `protobuf:"bytes,5,opt,name=vpn_ip,json=vpnIp,proto3" json:"vpn_ip,omitempty"`
	LocalServices map[string]uint32      `protobuf:"bytes,6,rep,name=local_services,json=localServices,proto3" json:"local_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // name -> port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceInfo) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceInfo) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *ResourceInfo) GetBackendMode() string {
	if x != nil {
		return x.BackendMode
	}
	return ""
}

func (x *ResourceInfo) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

func (x *ResourceInfo) GetLocalServices() map[string]uint32 {
	if x != nil {
		return x.LocalServices
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdepJson      []byte                 `protobuf:"bytes,1,opt,name=adep_json,json=adepJson,proto3" json:"adep_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateRequest) GetAdepJson() []byte {
	if x != nil {
		return x.AdepJson
	}
	return nil
}

type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SystemStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendMode   string                 `protobuf:"bytes,1,opt,name=backend_mode,json=backendMode,proto3" json:"backend_mode,omitempty"` // "cpu", "gpu", "mock"
	VpnIp         string                 `protobuf:"bytes,2,opt,name=vpn_ip,json=vpnIp,proto3" json:"vpn_ip,omitempty"`                   // Headscale IP
	Capsules      []*CapsuleInfo         `protobuf:"bytes,3,rep,name=capsules,proto3" json:"capsules,omitempty"`
	Resources     *ResourceUsage         `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *SystemStatus) GetBackendMode() string {
	if x != nil {
		return x.BackendMode
	}
	return ""
}

func (x *SystemStatus) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

func (x *SystemStatus) GetCapsules() []*CapsuleInfo {
	if x != nil {
		return x.Capsules
	}
	return nil
}

func (x *SystemStatus) GetResources() *ResourceUsage {
	if x != nil {
		return x.Resources
	}
	return nil
}

type CapsuleInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                     // "running", "stopped", "failed"
	LocalUrl          string                 `protobuf:"bytes,4,opt,name=local_url,json=localUrl,proto3" json:"local_url,omitempty"` // e.g., "http://app.local"
	ReservedVramBytes uint64                 `protobuf:"varint,5,opt,name=reserved_vram_bytes,json=reservedVramBytes,proto3" json:"reserved_vram_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapsuleInfo) Reset() {
	*x = CapsuleInfo{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleInfo) ProtoMessage() {}

func (x *CapsuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleInfo.ProtoReflect.Descriptor instead.
func (*CapsuleInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *CapsuleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapsuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapsuleInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CapsuleInfo) GetLocalUrl() string {
	if x != nil {
		return x.LocalUrl
	}
	return ""
}

func (x *CapsuleInfo) GetReservedVramBytes() uint64 {
	if x != nil {
		return x.ReservedVramBytes
	}
	return 0
}

type ResourceUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuCoresTotal    uint64                 `protobuf:"varint,1,opt,name=cpu_cores_total,json=cpuCoresTotal,proto3" json:"cpu_cores_total,omitempty"`
	CpuCoresUsed     uint64                 `protobuf:"varint,2,opt,name=cpu_cores_used,json=cpuCoresUsed,proto3" json:"cpu_cores_used,omitempty"`
	MemoryBytesTotal uint64                 `protobuf:"varint,3,opt,name=memory_bytes_total,json=memoryBytesTotal,proto3" json:"memory_bytes_total,omitempty"`
	MemoryBytesUsed  uint64                 `protobuf:"varint,4,opt,name=memory_bytes_used,json=memoryBytesUsed,proto3" json:"memory_bytes_used,omitempty"`
	VramBytesTotal   uint64                 `protobuf:"varint,5,opt,name=vram_bytes_total,json=vramBytesTotal,proto3" json:"vram_bytes_total,omitempty"`
	VramBytesUsed    uint64                 `protobuf:"varint,6,opt,name=vram_bytes_used,json=vramBytesUsed,proto3" json:"vram_bytes_used,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceUsage) GetCpuCoresTotal() uint64 {
	if x != nil {
		return x.CpuCoresTotal
	}
	return 0
}

func (x *ResourceUsage) GetCpuCoresUsed() uint64 {
	if x != nil {
		return x.CpuCoresUsed
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytesTotal() uint64 {
	if x != nil {
		return x.MemoryBytesTotal
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytesUsed() uint64 {
	if x != nil {
		return x.MemoryBytesUsed
	}
	return 0
}

func (x *ResourceUsage) GetVramBytesTotal() uint64 {
	if x != nil {
		return x.VramBytesTotal
	}
	return 0
}

func (x *ResourceUsage) GetVramBytesUsed() uint64 {
	if x != nil {
		return x.VramBytesUsed
	}
	return 0
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x15onescluster.engine.v1\x1a\fcommon.proto\"b\n" +
	"\n" +
	"LogRequest\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x04R\ttailLines\"Z\n" +
	"\x0eEngineLogEntry\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\x15\n" +
	"\x13GetResourcesRequest\"\x18\n" +
	"\x16GetSystemStatusRequest\"\xf8\x01\n" +
	"\rDeployRequest\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12!\n" +
	"\tadep_json\x18\x02 \x01(\fB\x02\x18\x01H\x00R\badepJson\x12'\n" +
	"\ftoml_content\x18\x05 \x01(\tB\x02\x18\x01H\x00R\vtomlContent\x12;\n" +
	"\brun_plan\x18\x06 \x01(\v2\x1e.onescluster.common.v1.RunPlanH\x00R\arunPlan\x12\x1b\n" +
	"\toci_image\x18\x03 \x01(\tR\bociImage\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digestB\n" +
	"\n" +
	"\bmanifest\"d\n" +
	"\x0eDeployResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tlocal_url\x18\x03 \x01(\tR\blocalUrl\",\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\"E\n" +
	"\fStopResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc8\x02\n" +
	"\fResourceInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x04R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x03 \x01(\x04R\tdiskBytes\x12!\n" +
	"\fbackend_mode\x18\x04 \x01(\tR\vbackendMode\x12\x15\n" +
	"\x06vpn_ip\x18\x05 \x01(\tR\x05vpnIp\x12]\n" +
	"\x0elocal_services\x18\x06 \x03(\v26.onescluster.engine.v1.ResourceInfo.LocalServicesEntryR\rlocalServices\x1a@\n" +
	"\x12LocalServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\".\n" +
	"\x0fValidateRequest\x12\x1b\n" +
	"\tadep_json\x18\x01 \x01(\fR\badepJson\"M\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xcc\x01\n" +
	"\fSystemStatus\x12!\n" +
	"\fbackend_mode\x18\x01 \x01(\tR\vbackendMode\x12\x15\n" +
	"\x06vpn_ip\x18\x02 \x01(\tR\x05vpnIp\x12>\n" +
	"\bcapsules\x18\x03 \x03(\v2\".onescluster.engine.v1.CapsuleInfoR\bcapsules\x12B\n" +
	"\tresources\x18\x04 \x01(\v2$.onescluster.engine.v1.ResourceUsageR\tresources\"\x96\x01\n" +
	"\vCapsuleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tlocal_url\x18\x04 \x01(\tR\blocalUrl\x12.\n" +
	"\x13reserved_vram_bytes\x18\x05 \x01(\x04R\x11reservedVramBytes\"\x89\x02\n" +
	"\rResourceUsage\x12&\n" +
	"\x0fcpu_cores_total\x18\x01 \x01(\x04R\rcpuCoresTotal\x12$\n" +
	"\x0ecpu_cores_used\x18\x02 \x01(\x04R\fcpuCoresUsed\x12,\n" +
	"\x12memory_bytes_total\x18\x03 \x01(\x04R\x10memoryBytesTotal\x12*\n" +
	"\x11memory_bytes_used\x18\x04 \x01(\x04R\x0fmemoryBytesUsed\x12(\n" +
	"\x10vram_bytes_total\x18\x05 \x01(\x04R\x0evramBytesTotal\x12&\n" +
	"\x0fvram_bytes_used\x18\x06 \x01(\x04R\rvramBytesUsed2\xc5\x04\n" +
	"\x06Engine\x12\\\n" +
	"\rDeployCapsule\x12$.onescluster.engine.v1.DeployRequest\x1a%.onescluster.engine.v1.DeployResponse\x12V\n" +
	"\vStopCapsule\x12\".onescluster.engine.v1.StopRequest\x1a#.onescluster.engine.v1.StopResponse\x12_\n" +
	"\fGetResources\x12*.onescluster.engine.v1.GetResourcesRequest\x1a#.onescluster.engine.v1.ResourceInfo\x12c\n" +
	"\x10ValidateManifest\x12&.onescluster.engine.v1.ValidateRequest\x1a'.onescluster.engine.v1.ValidationResult\x12e\n" +
	"\x0fGetSystemStatus\x12-.onescluster.engine.v1.GetSystemStatusRequest\x1a#.onescluster.engine.v1.SystemStatus\x12X\n" +
	"\n" +
	"StreamLogs\x12!.onescluster.engine.v1.LogRequest\x1a%.onescluster.engine.v1.EngineLogEntry0\x01B4Z2github.com/onescluster/coordinator/pkg/proto;protob\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_engine_proto_goTypes = []any{
	(*LogRequest)(nil),             // 0: onescluster.engine.v1.LogRequest
	(*EngineLogEntry)(nil),         // 1: onescluster.engine.v1.EngineLogEntry
	(*GetResourcesRequest)(nil),    // 2: onescluster.engine.v1.GetResourcesRequest
	(*GetSystemStatusRequest)(nil), // 3: onescluster.engine.v1.GetSystemStatusRequest
	(*DeployRequest)(nil),          // 4: onescluster.engine.v1.DeployRequest
	(*DeployResponse)(nil),         // 5: onescluster.engine.v1.DeployResponse
	(*StopRequest)(nil),            // 6: onescluster.engine.v1.StopRequest
	(*StopResponse)(nil),           // 7: onescluster.engine.v1.StopResponse
	(*ResourceInfo)(nil),           // 8: onescluster.engine.v1.ResourceInfo
	(*ValidateRequest)(nil),        // 9: onescluster.engine.v1.ValidateRequest
	(*ValidationResult)(nil),       // 10: onescluster.engine.v1.ValidationResult
	(*SystemStatus)(nil),           // 11: onescluster.engine.v1.SystemStatus
	(*CapsuleInfo)(nil),            // 12: onescluster.engine.v1.CapsuleInfo
	(*ResourceUsage)(nil),          // 13: onescluster.engine.v1.ResourceUsage
	nil,                            // 14: onescluster.engine.v1.ResourceInfo.LocalServicesEntry
	(*RunPlan)(nil),                // 15: onescluster.common.v1.RunPlan
}
var file_engine_proto_depIdxs = []int32{
	15, // 0: onescluster.engine.v1.DeployRequest.run_plan:type_name -> onescluster.common.v1.RunPlan
	14, // 1: onescluster.engine.v1.ResourceInfo.local_services:type_name -> onescluster.engine.v1.ResourceInfo.LocalServicesEntry
	12, // 2: onescluster.engine.v1.SystemStatus.capsules:type_name -> onescluster.engine.v1.CapsuleInfo
	13, // 3: onescluster.engine.v1.SystemStatus.resources:type_name -> onescluster.engine.v1.ResourceUsage
	4,  // 4: onescluster.engine.v1.Engine.DeployCapsule:input_type -> onescluster.engine.v1.DeployRequest
	6,  // 5: onescluster.engine.v1.Engine.StopCapsule:input_type -> onescluster.engine.v1.StopRequest
	2,  // 6: onescluster.engine.v1.Engine.GetResources:input_type -> onescluster.engine.v1.GetResourcesRequest
	9,  // 7: onescluster.engine.v1.Engine.ValidateManifest:input_type -> onescluster.engine.v1.ValidateRequest
	3,  // 8: onescluster.engine.v1.Engine.GetSystemStatus:input_type -> onescluster.engine.v1.GetSystemStatusRequest
	0,  // 9: onescluster.engine.v1.Engine.StreamLogs:input_type -> onescluster.engine.v1.LogRequest
	5,  // 10: onescluster.engine.v1.Engine.DeployCapsule:output_type -> onescluster.engine.v1.DeployResponse
	7,  // 11: onescluster.engine.v1.Engine.StopCapsule:output_type -> onescluster.engine.v1.StopResponse
	8,  // 12: onescluster.engine.v1.Engine.GetResources:output_type -> onescluster.engine.v1.ResourceInfo
	10, // 13: onescluster.engine.v1.Engine.ValidateManifest:output_type -> onescluster.engine.v1.ValidationResult
	11, // 14: onescluster.engine.v1.Engine.GetSystemStatus:output_type -> onescluster.engine.v1.SystemStatus
	1,  // 15: onescluster.engine.v1.Engine.StreamLogs:output_type -> onescluster.engine.v1.EngineLogEntry
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	file_common_proto_init()
	file_engine_proto_msgTypes[4].OneofWrappers = []any{
		(*DeployRequest_AdepJson)(nil),
		(*DeployRequest_TomlContent)(nil),
		(*DeployRequest_RunPlan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
